### ISSUE TITLE
Component unmount causes script tag to run

### ISSUE THREAD

**Issue by EricFries** [froala/react-froala-wysiwyg#101]
I'm encountering a situation where script tags inside the code editor are running when the Froala component unmounts.  This occurs even if `htmlexecutescripts` is set to `false`.

I was able to reproduce this in the quick example here:  https://github.com/getbento/froala-js-eval-bug

I attempted to step through the unmount/destroy process, and it looks like for a brief moment all Froala elements disappear except the outer container (`.fr-box') and the editor's "model" value.  At this point the script immediately runs.  Any ideas?

**Comment by EricFries** [comment]
Any ideas here?

**Comment by stefanneculai** [comment]
Are you able to replicate this on a jsFiddle without React?  https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by EricFries** [comment]
@stefanneculai Yes, here's the fiddle with the same config as in the React example: https://jsfiddle.net/ericfries/e7jou8nL/1/

If you add something like `<script>alert('hello world')</script>` to the code view, it executes when you click the button to remove the editor.
