### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Bobwu1** [froala/react-froala-wysiwyg#104]
> The react-froala-wyswiyg project is under MIT license. However, in order to use Froala WYSIWYG HTML Editor plugin you should purchase a license for it.

What's the difference between the MIT and paid license requirements?

Can we use the react-froala-wyswiyg package without the HTML editor plugin in our react app?

**Comment by stefanneculai** [comment]
We made the react plugin licensed under MIT so that others can learn on how to build such components for JS plugins. The `react-froala-wyswiyg` uses the Froala WYSIWYG Editor which is paid and for which you should purchase a license: https://www.froala.com/wysiwyg-editor/terms.
