### ISSUE TITLE
Cursor Position Moves to Beginning of Text after editor.html.get()

### ISSUE THREAD

**Issue by osumac24** [froala/react-froala-wysiwyg#105]
If use the model option, my cursor jumps to the beginning of the text anytime I start typing.
```javascript
<FroalaEditor  
    tag="textarea"  
    model={this.state.pageContent || null}  
    config={{  
          heightMin: 500,  
          events: { 'froalaEditor.contentChanged': this.handleFroalaInput }  
    }}
 />
```

```javascript 
handleFroalaInput(e, editor) {  
    this.setState({
      pageContent: editor.html.get()
    });
}
```

If I remove the line `model={this.state.pageContent || null}` the editor works fine.  I tried following the solution listed here https://stackoverflow.com/a/32617760 but could not find any option to set the cursor or marker position (https://www.froala.com/wysiwyg-editor/docs/methods).

**Comment by osumac24** [comment]
I someone able to assist with this issue?

**Comment by mremil6** [comment]
not one..

**Comment by jennybean** [comment]
@osumac24, I struggled with this issue for quite a bit. The solution I found works for me:
```
editor.selection.save();
const html = editor.html.get(true);
```

[`selection.save`](https://www.froala.com/wysiwyg-editor/docs/methods#selection.save) saves the current selection by adding HTML markers.
You must then pass in `true` when calling [`html.get`](https://www.froala.com/wysiwyg-editor/docs/methods#html.get) to keep the selection markers, as the default value is false.

**Comment by stefanneculai** [comment]
The cursor is being moved to the beginning of the input because on contentChanged event you're most likely setting back some HTML in the editor. By doing this, the cursor position from the browser is being reset because the HTML does not contain information about selection.

**Comment by kevinhq** [comment]
> @osumac24, I struggled with this issue for quite a bit. The solution I found works for me:
> 
> ```
> editor.selection.save();
> const html = editor.html.get(true);
> ```
> [`selection.save`](https://www.froala.com/wysiwyg-editor/docs/methods#selection.save) saves the current selection by adding HTML markers.
> You must then pass in `true` when calling [`html.get`](https://www.froala.com/wysiwyg-editor/docs/methods#html.get) to keep the selection markers, as the default value is false.

Then , do you need to call editor.selection.restore() after editor.html.set(some_modified_html) ?

**Comment by tonilam** [comment]
> editor.selection.save();
> const html = editor.html.get(true);

I found using selection.clear() works if you want to blur the editor.
```
editor.selection.save();
const html = editor.html.get(true);
editor.selection.clear();
```

**Comment by coding-bird** [comment]
> The cursor is being moved to the beginning of the input because on contentChanged event you're most likely setting back some HTML in the editor. By doing this, the cursor position from the browser is being reset because the HTML does not contain information about selection.

is there a way to achieve this, maintaining the cursor while pasting back the content (basically the scenario of two way binding) where I am getting the content from the editor and setting it back ?

**Comment by brewern** [comment]
I'm also having this problem. I've tried saving the properties of editor.selection.get() into a Ref. Then setting that focus position back using editor.selection.setAtEnd(selectionRef.current.focusNode.parentNode), then calling restore on that selection. However, even this isn't setting the cursor back to its position.

The parent component of this editor is processing the whole model value, looking for shortcodes; it processes the text and places it back. This is what's causing the focus to be reset. I'm looking for a way to restore that focus position after this. My attempt to restore the focus using the code above is within a useEffect after the value of the editor has changed.

**Comment by brewern** [comment]
My issue above was resolved by simply preventing the parent from re-rendering a second time unnecessarily when no there was no value change, due to a useEffect. So did not have to use this selection restore approach.

**Comment by tom-nexudus** [comment]
I solved this issue using [snapshot](https://froala.com/wysiwyg-editor/v2-0/docs/methods#snapshot.get):

```js
editor.html.insert('string'); // add whatever you want to add
const snapshot = editor.snapshot.get(); // save the current state
handleChange(editor.html.get()); // update your app's state, which messes up froala
editor.snapshot.restore(snapshot); // restore the froala state back again
```

**Comment by atomcorp** [comment]
I solved this issue using [snapshot](https://froala.com/wysiwyg-editor/v2-0/docs/methods#snapshot.get):

```js
editor.html.insert('string'); // add whatever you want to add
const snapshot = editor.snapshot.get(); // save the current state
handleChange(editor.html.get()); // update your app's state, whose render messed up froala
editor.snapshot.restore(snapshot); // restore the froala state back again
```

**Comment by tszekely** [comment]
I fixed this issue on my side by using `React.memo` on the parent component, it should work with `PureComponent` also.

**Comment by lucabattistini** [comment]
This issue happens only if the model is not empty at the mount of the component.
I solved this issue by setting the initial value with `editor.html.set()` instead of the model props, but this will prevent any external updates from outside.

**Comment by nivapo95** [comment]
I had this issue with the `editor.html.set()`  and the `editor.selection.save()` did not work for me.

This is what worked for me:

```
const snapshot = editor.snapshot.get(); // save the current state
editor.html.set(content);
if(snapshot.ranges.length > 0){
    editor.snapshot.restore(snapshot); // restore
}
```

I am checking the snapshot ranges length because I want to save & restore the cursor position only when the user is typing and not when the code injects any html to the editor.
