### ISSUE TITLE
How to upload to S3

### ISSUE THREAD

**Issue by justinwjoyce** [froala/react-froala-wysiwyg#106]
I sm following the documentation of the froala editor [here](https://www.froala.com/wysiwyg-editor/docs/sdks/ruby/file-s3-upload). At the very bottom, you will find a script tag with jquery in it. I am wondering how I can replicate that but in React to use with this component. I have a config object setup with a key fileUploadToS3 that is an object with the keys listed in the docs along with a params object that has keys of acl, AWSAccessKeyId, policy, and signature. Any direction would be appreciated! Thank you

**Comment by nomadus** [comment]
Hi, you have to create backend method to get an AWS signature. If your backend happens to be java, then you can use what is done in https://github.com/froala/wysiwyg-editor-java-sdk. Basically, you need to create a configuration object and feed it into your Froala editor config.

**Comment by justinwjoyce** [comment]
Thank you for the help! I am using Rails on the back end and I followed the ruby sdk example app. I created the FroalaController on the backend a lot like what the example app has except I put in my credentials for aw in the options hash. In all the examples I am seeing jquery code like this `$('selector').froalaEditor({
  imageUploadURL: '/upload_image'
});` and I am wondering how you do the same in react.

**Comment by nomadus** [comment]
You do the same way, e.g. in my react code
`  setTimeout(() => {
                $('noteContent').froalaEditor('html.set', null);
            }, 100);`

And for Editor
`<Editor
                                    config={TOOLBAR_CONFIG}
                                    content={currentNoteData.noteContent}
                                    id='noteContent'
                                    placeholder={intl.formatMessage({
                                        id: 'NOTES.NOTE_CONTENT_PLACEHOLDER',
                                        defaultMessage: defaults['NOTES.NOTE_CONTENT_PLACEHOLDER']
                                    })}
                                    onChange={this._handleChange('noteContent')}
                                />`

**Comment by nomadus** [comment]
This piece of code I use to reset the value of Editor, as it does not clear content after I submit the page.

**Comment by justinwjoyce** [comment]
Thank you for the help @nomadus !!
