### ISSUE TITLE
How to reset editor content after submit

### ISSUE THREAD

**Issue by nomadus** [froala/react-froala-wysiwyg#107]
The editor content does not reset even if I pass an empty object after submitting the form. Shouldn't it reset to an empty value?

**Comment by nomadus** [comment]
The following helps when I reset the content after submit is clicked:
 $('noteContent').froalaEditor('html.set', null);

But is this the right way of dong so? Doesn't the editor auto update when data passed to it is null?

**Comment by stefanneculai** [comment]
@nomadus yep, it is the correct way of doing it.

**Comment by ahmedemarasure** [comment]
events: {
          initialized: () => {
            this.resetForm();
          },
        },

--------------------------
 methods: {
resetForm() {
      this.form.comment = null;
      this.$refs.editor.oldModel = null;
      this.$refs.editor._editor.html.set("");
      this.$refs.editor._editor.undo.saveStep();
      this.$refs.editor._editor.undo.reset();
      this.$v.$reset();
    },
}

**Comment by GeorgeAmir839** [comment]
asasasas
