### ISSUE TITLE
video.showInsertPopup() error when called from dropdown

### ISSUE THREAD

**Issue by ledicana** [froala/react-froala-wysiwyg#111]
When I try to add an 'insert video' option to a dropdown menu, the editor.video.showInsertPopup() function throws the following error:

![image](https://user-images.githubusercontent.com/26224536/47150640-7d7dd400-d2d7-11e8-9fef-000089931f43.png)

I presume that the failure was caused, because the video plugin tries to find the fr-command class with data-cmd 'insertVideo', which is undefined, since my dropdown has a different command value: 

![image](https://user-images.githubusercontent.com/26224536/47150770-ef561d80-d2d7-11e8-8ca8-a291804c8387.png)

When I try to rename the command of my dropdown to 'insertVideo', the insert video popup is shown. I would like to avoid this, however. Is there any other workaround to this problem? 

Thank you!

**Comment by stefanneculai** [comment]
@ledicana Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/. Also, please open this issue on the main repo: https://github.com/froala/wysiwyg-editor.

**Comment by ledicana** [comment]
@stefanneculai I'm not sure if this is a global Froala problem or only related to React. In plain JS + jQuery, I can't reproduce the problem. In this example, the video insert popup is shown:
https://jsfiddle.net/ledicana/kchzgqxa/5/

In React, however, I can't access 'this.video' in the callback of 'my_dropdown', like in this JSFiddle example. Instead, I access the video object through the config.events.froalaEditor.commands.after, with editor.video object. There, when I try to call editor.video.showInsertPopup(), I receive the error. Is there a way to call this function from 'my_dropdown' callback in React?

**Comment by stefanneculai** [comment]
It shouldn't be any difference from how React works and the editor. In custom dropdowns, the `this` object should have just the same behavior. Please make sure that you're using the latest 2.8.5 version in React as well. Also, check that you're including the video plugin.

**Comment by ledicana** [comment]
@stefanneculai True, I have been able to fetch the same `this` object inside the dropdown's callback. I've tried calling the video.showInsertPopup() from the callback, but I get the same error. 

I've updated the version to 2.8.5 and I'm sure that the video plugin is included, since the default 'insertVideo' toolbar option is working.

**Comment by ledicana** [comment]
@stefanneculai You can find the repo here: https://github.com/ledicana/react-froala-example
