### ISSUE TITLE
Popover Positions - No Smart positioning Right alignment

### ISSUE THREAD

**Issue by StevenHensgen** [froala/react-froala-wysiwyg#113]
It would be really good to be able to re-position popovers.  Currently it seems that each plugin defines its own opening position.

The issue I have is that if the **Link** toolbar item is the last icon then the popover extends half in and half out of the froala editor.  If the editor is sitting flush to the right or left of the page this will create horizontal scrollbar and half of the popover is cut off (with no way to scroll since popovers close when focus is lost).

I was looking for a global event that I could use to override popover position calculations & manually determine if all popovers need to be smart positioned, but I could not find one.

Any suggestions on this?

**Edit:** Looking further into this the popover is smart positioned if the icon is the first icon (left aligned), just not the last icon.

**Comment by stefanneculai** [comment]
@StevenHensgen do you think you could make a demo for this?

**Comment by stefanneculai** [comment]
It has already been fixed on the Github master (https://github.com/froala/wysiwyg-editor) and will be included in release 2.9.2.
