### ISSUE TITLE
Button edit image not showing

### ISSUE THREAD

**Issue by hcandia-lagash** [froala/react-froala-wysiwyg#114]
![image](https://user-images.githubusercontent.com/8668781/48716978-46148700-ebf7-11e8-873c-9424695b6b41.png)

The button for edit images (aviary) is not showing anymore, is this deprecated?

**Comment by hcandia-lagash** [comment]
I used the new image editor: https://www.froala.com/wysiwyg-editor/examples/tui-advanced-image-editor

**Comment by JCanlett** [comment]
SO did you get this figured out? I'm having the same issue and even the "JS Fiddle" example on froala docs doesn't work.

**Comment by hcandia-uala** [comment]
Did you include the scripts on your index html? I worked with react integration, and I have to include some libs in the package, the process was quite different between pure js and the fwk (npm module).

**Comment by JCanlett** [comment]
I did yes. Also note that i'm using the angular wrapper, so that adds its own issues. I'm wondering if the "image edit buttons" need to have another added as it doesn't look like this is a default, but again I cannot find that mentioned in the docs.

**Comment by hcandia-uala** [comment]
![image](https://user-images.githubusercontent.com/54329928/65708996-30b58800-e066-11e9-978d-1f3911969ca7.png)

This is what I did in my js file plus the reference of the js files from tui image in index.html.

![image](https://user-images.githubusercontent.com/54329928/65709147-8ab64d80-e066-11e9-8362-4f696f68130b.png)

**Comment by jordankittle** [comment]
None of my edit image buttons show in froala text editor used in  Strapi.  If you hover over where they should be, the tooltip appears, and clicking on the remove tooltip removes the image, but the SVG's are invisible.
