### ISSUE TITLE
The TUI editor doesn't seem to work in Reat App 

### ISSUE THREAD

**Issue by xxxhuizhang** [froala/react-froala-wysiwyg#115]
I use froala in a REACT  app ,  The TUI editor doesn't seem to work . I can see the new button Advanced edit in the image pop up menu but nothing happens when I click it.  i search google find the same issue  and that solved . 

https://www.froala.com/wysiwyg-editor/examples/tui-advanced-image-editor

include these js and css files. if i include these file it works. but i find these files are included in node_modules/froala_editor/html/3dr_party/tui/index.html , why the Tui-editor not work.

![image](https://user-images.githubusercontent.com/10243195/50502193-5e01e500-0a98-11e9-98e7-4b26e68f18ff.png)

sorry my poor english, i hope i explain  clearly.  happy new year.

##### Expected behavior.

Display the TUI editor on Advanced edit click in the image pop up menu.

##### Actual behavior.

Nothing happens when clicking the Advanced edit button.

##### Steps to reproduce the problem.

Insert an image via the Insert image button.
In the pop up image menu, click on Advanced edit.

##### OS.

mac os  mojave

##### Browser.

chrome  71.0.3578.98

**Comment by xxxhuizhang** [comment]
![image](https://user-images.githubusercontent.com/10243195/50812537-0f810000-134e-11e9-8853-897a7307cac5.png)

if you need a test page . please visite   http://yj.cbhlife.com/test/froala

@stefanneculai

**Comment by stefanneculai** [comment]
Please make sure that you include the TUI files as described on: https://www.froala.com/wysiwyg-editor/examples/tui-advanced-image-editor

**Comment by 204504bySE** [comment]
I found workaround.

```
import "froala-editor/css/froala_style.min.css";
import "froala-editor/css/froala_editor.pkgd.min.css";

// import CSS for tui-image-editor
import "tui-color-picker/dist/tui-color-picker.min.css";
import "tui-image-editor/dist/tui-image-editor.min.css";

import "froala-editor/css/third_party/image_tui.min.css";
import "froala-editor/js/plugins.pkgd.min.js";
import FroalaEditorComponent from "react-froala-wysiwyg";
import { useAsync } from "react-use";

const imageEditorImports = (async () => {
  // import tui-image-editor like <script> tag
  window["tui"] = window["tui"] || {};
  window["tui"]["ImageEditor"] = (await import("tui-image-editor")).default;
  await import("froala-editor/js/third_party/image_tui.min.js");
})();

const someComponentWithFroala = () => {
  const imports = useAsync(() => imageEditorImports, []);

  if(imports.loading) { return <></>; }
  
  return <FroalaEditorComponent />;
}

```
