### ISSUE TITLE
How to use the React Froala WYSIWYG component with LinkProtocols?

### ISSUE THREAD

**Issue by Canuckaholic** [froala/react-froala-wysiwyg#116]
##### Description of Issue:

I'm trying to use `LinkProtocols` as described here: https://github.com/froala/wysiwyg-editor/issues/2177, but this requires running it on the Froala object before it's initialized.

The React Froala WYSIWYG component (https://github.com/froala/react-froala-wysiwyg) allows you to initialize manually using `onManualControllerReady`, but I am not seeing any way to run LinkProtocols on the object before it is initialized.

As suggested in this issue: https://github.com/froala/wysiwyg-editor/issues/2177, it would be great to have a configuration option to be able to set the LinkProtocols, or alternatively if someone could tell me how to implement LinkProtocols with the React component...

**Comment by stefanneculai** [comment]
You could do it just as described on the other Github ticket. Make sure that you include the editor JS files before.

**Comment by Canuckaholic** [comment]
Thanks for replying @stefanneculai but I still don't see a way of doing something like this:

`$.FE.LinkProtocols = ['mailto', 'tel', 'sms', 'notes', 'data', 'gid'];`

when using the React Froala WYSIWYG component.

**Comment by Canuckaholic** [comment]
For anyone who stumbles across this issue... This seems to work:

Add something similar to the following to your React component that in turn is using the React Froala Editor component:

```
componentWillMount() {
    if ($.FroalaEditor.LinkProtocols.indexOf('itms-services') === -1) {
      $.FroalaEditor.LinkProtocols.push('gid', 'itms-services')
    }
  }
```
