### ISSUE TITLE
Custom Buttons Is not Working in ReactJS

### ISSUE THREAD

**Issue by vijayshukla30** [froala/react-froala-wysiwyg#119]
I follow your #77 ,but it doesn't work for me.
![image](https://user-images.githubusercontent.com/11537372/51300141-e1d43f00-1a50-11e9-9a6d-c050ad99111d.png)
![image](https://user-images.githubusercontent.com/11537372/51300161-f0baf180-1a50-11e9-9f3c-73d712218b5e.png)
I also imported $.
import $ from "jquery";

**Comment by vijayshukla30** [comment]
How can I upload audio in the editor? To resolve this I thought to add a custom button to handle the upload.

**Comment by vijayshukla30** [comment]
It works, instead of of creating custom button in componentDidMount, I created it in render() just before config.

**Comment by vijayshukla30** [comment]
But, please help me to add audio upload option in Editor.

**Comment by stefanneculai** [comment]
@vijayshukla30 could you please request it here: https://wysiwyg-editor-roadmap.froala.com/public.

**Comment by jyhong666** [comment]
Froala is removing dependence on JQuery, so what is the proper way to add a customize button for now?
