### ISSUE TITLE
How to Invoke Editor Event programmatically in React?

### ISSUE THREAD

**Issue by bernardworthy** [froala/react-froala-wysiwyg#12]
I really like the Froala product, but I'm not quite sure how to invoke editor events programmatically in React. What would the equivalent implementation of the method invocation below look like in React? 

$('.selector').froalaEditor('fullscreen.toggle');

Also, is there a better way to initialize the editor in fullscreen mode?

**Comment by stefanneculai** [comment]
Please see: https://github.com/froala/react-froala-wysiwyg#events-and-methods. You could subscribe to initialized event and do all the things you want there directly on the editor object: `editor.fullscreen.toggle()`.

**Comment by furkanedu** [comment]
Where is this editor object ? Link given is not explaining the answer.

**Comment by Alchemist-V** [comment]
I guess we can attach call methods to various events exposed by froala, this can be passed in the editor config.
{
  'events' : {
       'froalaEditor.focus' : function(e, editor) {
        }
    }
}

**Comment by stefanneculai** [comment]
@Alchemist-V that is correct.

**Comment by Alchemist-V** [comment]
Thanks @stefanneculai , though i am still trying to figure out which event should i subscribe to, to perform some 'onHover' action on an HTML element? Can you please throw some light ?

**Comment by Alchemist-V** [comment]
to be more descriptive.. here is what i am trying to achieve
events : {
            'froalaEditor.initialized': function(e, editor) {
                var elements = document.getElementsByClassName('some-class-id-that-i-know-exists');
                for (var i=0; i< elements.length ; i++) {
                    elements[i].addEventListener('mouseover', eventListnerSubscriber(elements[i]), true);
                }
            }
        }

// outside config
function eventListnerSubscriber(element) {
      console.log(element);
}
here the callback method 'eventListnerSubscriber ' upon event mouseover is not getting invoked.

I have raised the same on SO here https://stackoverflow.com/questions/45642461/unable-to-attach-event-listeners-to-element-rendered-in-froala-rich-text-editor

**Comment by stefanneculai** [comment]
@Alchemist-V most likely you are doing something wrong. Here is how I tested it and works fine:

```jsx
// Render Froala Editor component.
class EditorComponent extends React.Component {
  constructor() {
    super();

    this.state = {
      content: '<div class="foo">asdasdasd</div>'
    };

    this.config = {
      events : {
        'froalaEditor.initialized': function(e, editor) {
          var elements = document.getElementsByClassName('foo');
          for (var i=0; i< elements.length ; i++) {
            elements[i].addEventListener('mouseover', function () {
              console.log ('foo')
            }, true);
          }
        }
      }
    }

    this.handleModelChange = this.handleModelChange.bind(this);
  }

  handleModelChange (model) {
    this.setState({
      content: model
    });
  }

  render () {
    return(
      <div className="sample">
        <h2>Full Featured</h2>
        <FroalaEditor
          model={this.state.content}
          onModelChange={this.handleModelChange}
          config={this.config}
        />
        <h4>Rendered Content:</h4>
        <FroalaEditorView
          model={this.state.content}
        />
      </div>
    );
  }

}

ReactDOM.render(<EditorComponent/>, document.getElementById('editor'));
```

**Comment by adueck** [comment]
> Please see: https://github.com/froala/react-froala-wysiwyg#events-and-methods. You could subscribe to initialized event and do all the things you want there directly on the editor object: `editor.fullscreen.toggle()`.

Forgive my lack of understanding, but I am confused. Could you please explain how to 'subscripbe to the initialized event'? Once the editor initializes, I would like to be able to problematically do things to to the editor from outside of the editor component.
