### ISSUE TITLE
Help, I can't run it :'(

### ISSUE THREAD

**Issue by Chococoin** [froala/react-froala-wysiwyg#124]
Sorry, I have to admit that I'm too noob to run this repo. I have spent several hours trying to success. 

My goal is to run the froalaEditor using react in an Electron app. 

But at the moment I'll be happy to achieve to use the froalaEditor component in an ejected CRA.

Is possible to ask for a hand? Or ask if you know where can I find a running boilerplate?

Thank you for your time.

**Comment by ilyaskarim** [comment]
Here is a demo: https://github.com/ilyaskarim/froala-react-boilerplate for react app, You can use same procedure for Electron + React app.
