### ISSUE TITLE
New master fixes

### ISSUE THREAD

**Issue by alassiter** [froala/react-froala-wysiwyg#13]
There have been some fixes to the master froala editor not included in 2.4.0 which is the latest this repo is based on. I'm not as familiar with npm perhaps as I should. How can I update to the newest master commits? Or would you be willing to merge master in again here so I can update?

I need one of the fixes that was made

Thank you

**Comment by stefanneculai** [comment]
@alassiter Updates are being pushed here only after the official release is made.
