### ISSUE TITLE
Help! I Can't run it under typescript!

### ISSUE THREAD

**Issue by jyhong666** [froala/react-froala-wysiwyg#132]
Help! I Can't run it!
I wrote react using typescript

Failed to compile
C:/VS_Test/createReactApp/reactapptest/src/index.tsx
(1,21): <reference> is not allowed, use imports

///<reference path="../node_modules/react-froala-wysiwyg/index.d.ts"/>

import * as React from 'react';
import * as ReactDOM from 'react-dom';
// Require Editor JS files.
import 'froala-editor/js/froala_editor.pkgd.min.js';

// Require Editor CSS files.
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

// Require Font Awesome.
import 'font-awesome/css/font-awesome.css';

import {FroalaEditor} from 'react-froala-wysiwyg';

ReactDOM.render(<FroalaEditor/>, document.getElementById('root'));

_Originally posted by @jyhong666 in https://github.com/froala/react-froala-wysiwyg/issues/16#issuecomment-476046888_

**Comment by stefanneculai** [comment]
Please follow https://github.com/froala/react-froala-wysiwyg#using-type-definition-file

**Comment by jyhong666** [comment]
I see,but I can't run it!
Please give me a sample?
thanks!

**Comment by jyhong666** [comment]
> Please follow https://github.com/froala/react-froala-wysiwyg#using-type-definition-file

I see,but I can't run it!
Please give me a sample?
thanks!

**Comment by gcrtime** [comment]
the same to me, how to use it In typescript

**Comment by brandonmp** [comment]
the directions are a little unclear, but adding this to the top of the file where I was using Froala is what worked for me:
```
///<reference path= "../../../../node_modules/react-froala-wysiwyg/lib/index.d.ts" />
```

**Comment by jyhong666** [comment]
> the directions are a little unclear, but adding this to the top of the file where I was using Froala is what worked for me:
> 
> ```
> ///<reference path= "../../../../node_modules/react-froala-wysiwyg/lib/index.d.ts" />
> ```

Yes,me too.

**Comment by aalpgiray** [comment]
why it is not picked up automatically, just like any other library?

**Comment by mrfambo** [comment]
Such a pathetic support for Typescript. index.d.ts file had to be in the root, if not possible you could have mentioned it in your package.json so typescript can pull it automatically.
**(Paid User of Froala)**
