### ISSUE TITLE
v2.9.4 – Module not found: Error: Can't resolve 'react-froala-wysiwyg'

### ISSUE THREAD

**Issue by rpearce** [froala/react-froala-wysiwyg#135]
Hi, wonderful Froala people,

With the latest `2.9.4` release, is it possible that the module exporting changed? I took a look at the `main` `package.json` property, and it points to `index.js`, but I can't find an `index.js` at the project root in either GitHub or in the released module.

Is it possible that something went amiss with the release? Is there no more default export for the package? Am I just doing it wrong?

Thanks for the help,
Robert

**Comment by rpearce** [comment]
Also, I've noticed that the version here is `2.9.4`, as is latest `froala-editor` package, but it looks like `froala-editor` dependency in this project is set to `2.9.3`:
https://github.com/froala/react-froala-wysiwyg/blob/4caf2d0c642aa79f1cb072683ef0c4ca5d3bf671/package.json#L27

Should this be `2.9.4`, or is that something you'll get to later?

**Comment by rpearce** [comment]
Update: looks like `froala-editor` has been bumped to `2.9.4` in dependencies:
https://github.com/froala/react-froala-wysiwyg/blob/master/package.json#L27

Going to give it a whirl. Standby...

**Comment by rpearce** [comment]
Okay, this is resolved in `2.9.4-1` that was merged ~5 hours ago. Thanks!

**Comment by vladpavlovski** [comment]
> Okay, this is resolved in `2.9.4-1` that was merged ~5 hours ago. Thanks!

Hi, today this library was update to `2.9.5`. and looks like it has the same issue. @rpearce can you please check it?

**Comment by rpearce** [comment]
@vladpavlovski I'm out for the weekend and don't work for Froala. I recommend opening a new issue!
