### ISSUE TITLE
Unable to initialize FroalaEditor in React

### ISSUE THREAD

**Issue by ewittle** [froala/react-froala-wysiwyg#14]
I'm trying to evaluate froala-editor for a React project, but I'm not getting it to work. I believe I've followed the instructions, with no luck.

1) Edited the webpack.config.js file to include the following plugin:

```
    plugins: [
      new webpack.DefinePlugin({
        'process.env': {
          'NODE_ENV': JSON.stringify('production')
        }
      }),
	  new webpack.DefinePlugin({
		$: "jquery",
		jQuery: "jquery"
	  })
	],
```

2) Imported / required the necessary code:

```
import $ from 'jquery'
import jQuery from 'jquery'

window.$ = $
window.jQuery = jQuery

// Not in instructions, added to resolve "jquery not defined" in browser console
window.jquery = jQuery

// Require Editor JS files.
require('froala-editor/js/froala_editor.pkgd.min.js')
require('froala-editor/css/froala_editor.pkgd.min.css')

// Require Font Awesome.
require('font-awesome/css/font-awesome.css')

var FroalaEditor = require('react-froala-wysiwyg')

```
3) Included the following JSX in my render method.

```
            <textarea id='EditorArea' />
            <FroalaEditor tag='EditorArea' />

```

4) When running the page with the above configuration, I get:

`TypeError: this.$element.froalaEditor is not a function`

5) If I remove the assignment of window.jquery = jQuery mentioned in (2) above, I get:

`ReferenceError: jquery is not defined`

I expect this means I'm somehow not including jQuery correctly in the project, but I'm unable to determine why. Any suggestions would be helpful.

**Comment by ewittle** [comment]
OK, figured it out after some more googling & experimenting. In the above code, my webpack.config.js plugin statement is wrong, I used "webpack.DefinePlugin" instead of "webpack.ProvidePlugin" to enable jQuery. The other error is because I was not providing the model or onModelChange parameters to FroalaEditor.

Suggested enhancement would be if either of these parameters (model and onModelChange) are required, you throw a more useful error message when they're missing.

**Comment by ewittle** [comment]
OK, declared victory prematurely, not sure why I thought the editor was working, I had a plain text area. I'm still seeing the TypeError: this.$element.froalaEditor is not a function. Updated JSX:

```
            <FroalaEditor tag='textarea'
                          model={this.state.model}
                          config={FroalaConfig}
                          onModelChange={this.handleModelChange} />
```

and the state is:

```
    this.state = {
      value: 10,
      fileSet: [],
      model: 'Example Text'
    }
```

And the onModelChange declaration is:

```
  handleModelChange (model) {
    this.setState({model: model})
  }
```

**Comment by ewittle** [comment]
After further research / debugging, there is some issue with jQuery initialization when following the project docs. I was able to work around this by loading jQuery via script tags rather than including directly in the project via npm, and referencing jQuery as an external dependency in webpack with the following:

```
  externals: {
    facebook: "FB"
//    jquery: "$"
```

It is still possible that I'm doing something wrong, but I have no issues with including jQuery as a dependency in this manner, so feel free to close the issue if this is not repeatable outside my config.

**Comment by stefanneculai** [comment]
@ewittle thanks for clarifying this.

**Comment by arkitex** [comment]
fwiw, I had this same problem. It turns out that I had noParse set in my webpack config, which does not work with ProvidePlugin. Removing noParse made it work.

**Comment by MJfenix** [comment]
@ewittle where exactly in webpack did you specify jquery as an external dependency. Fwiw, I am not using webpack, and getting the same error

**Comment by wittlesouth** [comment]
In the web pack.config.js, the relevant sections (as I understand it) are in plugins, where I have:

```
    new webpack.ProvidePlugin({
      "FB": "facebook",
      "$": "jquery",
      "jQuery": "jquery"
    }),
```

and in Externals, where I have:

```
  externals: {
    facebook: "FB",
    jquery: "$"
  },
```

Because I marked jQuery as external, I needed the following in the main HTML page of the app:

```
    <!-- Include external jquery Froala dependency -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
```

So this is basically avoiding using web pack to package a jQuery version from node_modules, and instead requiring the browser to load it independently. No matter what I tried, I was unable to get the editor to initialize correctly unless jQuery was handled as an external dependency. I filed a ticket with Froala, and they were unable to reproduce the problem.

**Comment by srosset81** [comment]
Since this package is a simple wrapper around Froala, it's easy to copy it and import the jquery module in case you don't manage to do a global import in your configuration.

See this: https://gist.github.com/srosset81/1a9e04340ef23fb8c9f4872b38e701ee
