### ISSUE TITLE
[3.0.0-beta.1] Uncaught TypeError: o.default is not a constructor

### ISSUE THREAD

**Issue by abdullahtariq1171** [froala/react-froala-wysiwyg#143]
Using latest version `3.0.0-beta.1` throws this error

> index.js?3b03:1 Uncaught TypeError: o.default is not a constructor
>     at t.value (index.js?3b03:1)
>     at t.value (index.js?3b03:1)
>     at commitLifeCycles (react-dom.development.js?cada:17334)
>     at commitAllLifeCycles (react-dom.development.js?cada:18736)
>     at HTMLUnknownElement.callCallback (react-dom.development.js?cada:149)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js?cada:199)
>     at invokeGuardedCallback (react-dom.development.js?cada:256)
>     at commitRoot (react-dom.development.js?cada:18948)
>     at eval (react-dom.development.js?cada:20418)
>     at Object.unstable_runWithPriority (scheduler.development.js?767c:255)

**Comment by rares-lupascu** [comment]
same here

**Comment by Farhan-Haseeb** [comment]
facing same problem (using react)

**Comment by stefanneculai** [comment]
Thanks for reporting this. We can confirm the problem and we're working on it - there should be a fix in the upcoming hours.

**Comment by ahadortiz** [comment]
facing same problem
would you like to let me know the working version for temp solution?

**Comment by abdullahtariq1171** [comment]
the issue is solved latest release `3.0.0-beta.1-1`.

**Comment by nikpok** [comment]
verified.its fixed now
