### ISSUE TITLE
Error importing froala editor: Uncaught TypeError: Illegal invocation 

### ISSUE THREAD

**Issue by epacuit** [froala/react-froala-wysiwyg#149]
Webpack version 4.

Froala editor version: 
    "react-froala-wysiwyg": "^3.0.0-beta.1-1",
    "froala-editor": "^3.0.0-beta.1",

Here is how I am importing froala: 

// Require Editor CSS files.
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

//import 'froala-editor/js/plugins/lists.min.js';
import 'froala-editor/js/plugins/image.min.js';
import 'froala-editor/css/plugins/image.min.css';
import 'froala-editor/js/plugins/image_manager.min.js';
import 'froala-editor/css/plugins/image_manager.min.css';

import FroalaEditorComponent from 'react-froala-wysiwyg';
import FroalaEditorView from 'react-froala-wysiwyg/FroalaEditorView';

When loading my app, I get the following error: 

Uncaught TypeError: Illegal invocation
    at Node.get (froala_editor.pkgd.min.js:1)
    at froala_editor.min.js:1
    at froala_editor.min.js:1
    at Object.<anonymous> (froala_editor.min.js:1)
    at t (bootstrap e2c5a3a0bafb5a939666:54)
    at image.min.js:1
    at Object.<anonymous> (image.min.js:1)
    at t (bootstrap e2c5a3a0bafb5a939666:54)

**Comment by stefanneculai** [comment]
Please update to `3.0.0-beta.2` - should fix it.
