### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by tsusini** [froala/react-froala-wysiwyg#150]
I use the latest version but it seems we still need importing jQuery..

**Comment by stefanneculai** [comment]
@tsusini what are you doing when getting this error? Are you using 3.0.0-beta.2?

**Comment by sabativi** [comment]
Hello,

This is inside my package.json and `"react-froala-wysiwyg": "^3.0.0-beta.2"` and I have this error

**Comment by stefanneculai** [comment]
@sabativi can you send us a screenshot of the error you're getting?

**Comment by nikolap** [comment]
If you downgrade to `"react-froala-wysiwyg": "3.0.0-beta.1-1"` it goes away, so probably some sort of regression with this version.

**Comment by stefanneculai** [comment]
@nikolap it shouldn't as we haven't made any changes related to that. Is it possible to replicate a demo?

**Comment by nikolap** [comment]
Sure, I'll look into creating a demo later today or Wednesday. 

We're testing it in Clojurescript so it would take me a bit to figure out how to create a JS React project, but the functionality of our tests are very basic (create a single FroalaEditor component with the `"textarea"` tag) -- it works for some reason with `3.0.0-beta.1-1` but not with `3.0.0-beta.2` failing with the error indicated in this issue.

**Comment by nikolap** [comment]
@stefanneculai Never mind, that was easier to do than I thought. Here you are: https://github.com/nikolap/froala-issue

**Comment by Clarity-89** [comment]
Having the same issue and downgrading to `3.0.0-beta.1-1` fixes it.

**Comment by stefanneculai** [comment]
Should be good in `3.0.0-beta.2-1`. Thanks for the help in fixing it.
