### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by Clarity-89** [froala/react-froala-wysiwyg#157]
After updating to rc-2 started getting `TypeError: Cannot read property 'ownerDocument' of null` on init. The editor was working fine before that.
Can't show a meaningful stack trace thing the whole thing is minified, but here's what I see:
```
froala_editor.min.js?b1fc:7 Uncaught TypeError: Cannot read property 'ownerDocument' of null
    at new b.Bootstrap (froala_editor.min.js?b1fc:7)
    at new B (froala_editor.min.js?b1fc:7)
    at t.value (index.js?fc18:1)
    at t.value (index.js?fc18:1)
```

**Comment by navneetnagpal** [comment]
Fixed in latest version. 3.0.0-rc.2-1

**Comment by heavenlian** [comment]
still happen react-froala-wysiwyg@4.0.11:

**Comment by heavenlian** [comment]
![Uploading image.png…]()
