### ISSUE TITLE
3.0.0-rc.2 Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by rares-lupascu** [froala/react-froala-wysiwyg#158]
i do not get this on rc1

![Screenshot 2019-06-06 at 20 41 26](https://user-images.githubusercontent.com/3641866/59054042-7eca3400-889b-11e9-8329-54a1620b6b18.png)

**Comment by johanventer** [comment]
Same issue here.

**Comment by Snivik** [comment]
As in versions before 3.0.0, import jquery manually and place it as $ in window/global. 

import $ from 'jquery';
global['$'] = $;

**Comment by navneetnagpal** [comment]
Fixed! and released 3.0.0-rc.2-1.

**Comment by gondar00** [comment]
Still facing the same issue
