### ISSUE TITLE
Add type definition files

### ISSUE THREAD

**Issue by monolithed** [froala/react-froala-wysiwyg#16]
It would be nice to have `*.d.ts` files. These files are used to provide TypeScript type information about an API that's written in JavaScript. They can be added directly here or to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) (`@types/react-froala-wysiwyg`).

**Comment by Aaronik** [comment]
These would be very useful - are there any plans to add these?

**Comment by stefanneculai** [comment]
Yes, we're going to add them shortly.

**Comment by atrauzzi** [comment]
Looking forward to this!

**Comment by yvanwangl** [comment]
I also hope to add .d.ts file for typescript !

**Comment by yenshih** [comment]
Any updates about type definition?

**Comment by ekiliqua** [comment]
UP!

Any updates about this?

Thanks.

**Comment by jyhong666** [comment]
Help! I Can't run it!

Failed to compile
C:/VS_Test/createReactApp/reactapptest/src/index.tsx
(1,21): <reference> is not allowed, use imports


///<reference path="../node_modules/react-froala-wysiwyg/index.d.ts"/>

import * as React from 'react';
import * as ReactDOM from 'react-dom';
// Require Editor JS files.
import 'froala-editor/js/froala_editor.pkgd.min.js';

// Require Editor CSS files.
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

// Require Font Awesome.
import 'font-awesome/css/font-awesome.css';

import {FroalaEditor} from 'react-froala-wysiwyg';

ReactDOM.render(<FroalaEditor/>, document.getElementById('root'));
