### ISSUE TITLE
Inserting a video makes entire fr-view div a click event for the video

### ISSUE THREAD

**Issue by nathanfriemel** [froala/react-froala-wysiwyg#17]
I've noticed this behavior on my local implementation and in the full_editor.html example; after adding a video by URL or Embedded code the entire editable area becomes a click event on the video.  The only way to continue editing is to blur out of the editor and click one of the toolbar buttons which will place your cursor at the very top.

**Comment by stefanneculai** [comment]
Hi @nathanfriemel! Unfortunately, the browsers have some limitations in this case and we cannot do much about it. For this case, we created the Line Breaker plugin which would should a helper to insert a new line above/below of the video when you go with the mouse on the top/bottom of the video.

**Comment by nathanfriemel** [comment]
I'd be remiss if I didn't ask, what are the specific browser limitations you speak of?

**Comment by stefanneculai** [comment]
In order to allow video selection and fancy stuff like dragging it around the editable area, we have to use some additional markup which when video is displayed as a block fills the entire.

**Comment by nathanfriemel** [comment]
I enabled and played around with the Line Breaker plugin; added a video, clicked the line break circle, cursor placed inline after the video (the top of video lineBreaker also appears near the bottom of the video, a different problem), at this point I can enter text, select toolbar buttons and it's generally fine as long as you stick to the keyboard, however once you click to position your cursor anywhere else the video is selected and the videoEditButtons are shown.

**Comment by DmitriWolf** [comment]
I would like to confirm after extensive testing this is a real bug and the proposed solution of using the Line Breaker plugin does not work, as described by nathan friemel in the comment above.

@stefanneculai  Please re-open this bug. We are currently searching for other solutions for adding video because this product does not work.
