### ISSUE TITLE
V 2.9.6 && V 3.0.1 Module not found: Error: Can't resolve 'react-froala'

### ISSUE THREAD

**Issue by KanzariAmine** [froala/react-froala-wysiwyg#171]
![console](https://user-images.githubusercontent.com/18327449/60445349-f24f2f00-9c16-11e9-8263-d849fd935330.png)

**Comment by karanjariwala** [comment]
This is still happening. Can you guys resolve this soon.

**Comment by casualuser** [comment]
Hi 

So this is wrong spelling for the package name. There is no package 'react-froala' but the proper name is 'react-froala-wysiwyg'.

```
➜  npm install react@16 react-dom@16 react-froala-wysiwyg@2.9.6
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-test@1.0.0 No description
npm WARN react-test@1.0.0 No repository field.

+ react-froala-wysiwyg@2.9.6
+ react-dom@16.9.0
+ react@16.9.0
added 26 packages from 99 contributors and audited 46 packages in 27.907s
found 0 vulnerabilities
```

**Comment by karanjariwala** [comment]
Even with the correct name it is not working.  open the browser for v2.9.6 it is not working. 

<img width="1680" alt="Screenshot 2019-08-19 at 8 01 13 PM" src="https://user-images.githubusercontent.com/9664177/63273766-2e6c4b00-c2bc-11e9-9ae3-baf85909195d.png">

**Comment by karanjariwala** [comment]
> Hi
> 
> So this is wrong spelling for the package name. There is no package 'react-froala' but the proper name is 'react-froala-wysiwyg'.
> 
> ```
> ➜  npm install react@16 react-dom@16 react-froala-wysiwyg@2.9.6
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN react-test@1.0.0 No description
> npm WARN react-test@1.0.0 No repository field.
> 
> + react-froala-wysiwyg@2.9.6
> + react-dom@16.9.0
> + react@16.9.0
> added 26 packages from 99 contributors and audited 46 packages in 27.907s
> found 0 vulnerabilities
> ```

@casualuser
Even with the correct name it is not working. open the browser for v2.9.6 it is not working.
It just install successfully.
<img width="1680" alt="Screenshot 2019-08-19 at 8 01 13 PM" src="https://user-images.githubusercontent.com/9664177/63273838-5360be00-c2bc-11e9-8434-3f23fa2021c4.png">
