### ISSUE TITLE
Whats the status for react-froala-wysiwyg 3

### ISSUE THREAD

**Issue by jEnbuska** [froala/react-froala-wysiwyg#172]
We are just started to integrate react-froala-wysiwyg into our project to see how it works out. 
I noticed that froala-editor 3 was released just a few weeks ago, so I'm wondering when will react-froala-wysiwyg 3 come out, and what kind of breaking changes can we expect?

**Comment by aliaksandr-yanchuk** [comment]
We did the integration of 3.0.1 as well and stumbled upon a stop-ship issue with inline editor, its already described in issues here: https://github.com/froala/react-froala-wysiwyg/issues/170
