### ISSUE TITLE
Can't resolve 'react-froala-wysiwyg' with create-react-app

### ISSUE THREAD

**Issue by jEnbuska** [froala/react-froala-wysiwyg#173]
Is it possible to use react-froala-wysiwyg with create-react-app without ejecting?
I'm currently getting this error:
`
Module not found: Can't resolve 'react-froala-wysiwyg' in '/usr/src/app/src/<...>'
`
node_modules/react-froala-wysiwyg/package.json seems to point to index.js file that does not exist and the module does not seem to contain any transpiled js.

Do the basic/pro version also have these same issues?

**Comment by gregoryforel** [comment]
[Here](https://codesandbox.io/s/froala-react-xrqvj)
