### ISSUE TITLE
Events props undefined

### ISSUE THREAD

**Issue by jmlopezo** [froala/react-froala-wysiwyg#175]
Events props returns undefined, event(e) and editor..

events: {
                'initialized': function (e, editor) {
                    console.log(e, editor)
                    editor.edit.off();
                },
                'focus': function (e, editor) {
                    console.log(editor.selection.get());
                }
            }

**Comment by faizanathar** [comment]
Facing same issue.

**Comment by sach185** [comment]
+1

**Comment by jmlopezo** [comment]
To reference the instance of the editor you have to use this.

Ej:

new FroalaEditor('.selector', {
  events: {
    'codeView.update': function () {
      // Do something here.
      // this is the editor instance.
      console.log(this);
    })
  }
});

**Comment by abdullahtariq1171** [comment]
> To reference the instance of the editor you have to use this.
> 
> Ej:
> 
> new FroalaEditor('.selector', {
> events: {
> 'codeView.update': function () {
> // Do something here.
> // this is the editor instance.
> console.log(this);
> })
> }
> });

Looks like you're bypassing the react-froala-wysiwyg? If so then this is more of a temporary workaround than solution.

**Comment by kjain-dev** [comment]
Facing same issue for focus event
