### ISSUE TITLE
Unable to add the License Key

### ISSUE THREAD

**Issue by granjan** [froala/react-froala-wysiwyg#18]
In order to active the license you have purchased generate a key below and then add the following code after you include the editor JS files.

<script>
$.FroalaEditor.DEFAULTS.key = 'ACTIVATION_KEY';
</script>

OR, pass the key as an option when you initialize the editor.

<script>
$(your_selector).froalaEditor({key: 'ACTIVATION_KEY'});
</script>

I am currently trying to do this in my project but I still see the Unlicensed tag on the editor.
Could Find no documentation here on this.

I tried adding these lines in **componentDidMount** & **componentWillReceiveProps**.
Is there something I am missing.

**Comment by stefanneculai** [comment]
You should include the key just after the editor JS is loaded `$.FroalaEditor.DEFAULTS.key = ''`.

**Comment by Oscuro87** [comment]
What are the lines you used to initialise the license key?
I tried many different options but can't seem to find anything in the holy documentation.
Ty in advance.

**Comment by stefanneculai** [comment]
@Oscuro87 the details can be found on your account fromFroala.com. Please reach us via our website (https://www.froala.com/wysiwyg-editor/contact) and our support team will assist you.

**Comment by Oscuro87** [comment]
Hello Stefan,

Indeed, I have logged in and could see how to do this.
I was about to edit the comment but you were quick :D
Thank you for the nice work on this!

Best regards

**Comment by raphaelbeckmann** [comment]
I have the same problem as @Oscuro87 but cannot solve it.

I imported react-froala like this `import FroalaEditor from 'react-froala-wysiwyg';`.

On my account at Froala.com it's saying I have to add the license key like this:

```
$(your_selector).froalaEditor({
    key: 'ACTIVATION_KEY'
});
```

But that's jQuery code, no react code, and of course I don't have a jQuery selector.

@stefanneculai can you please help again?

**Comment by trainbolt** [comment]
I have the same exact problem. Pointing people to contact on the website is just bad customer service. It does no harm to just let people know right here what the proper code is for a React project. Does the React FroalaEditor component have a 'key' prop for this? It's a simple question/answer that could potentially help a lot of people.
