### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by endlessdev** [froala/react-froala-wysiwyg#185]
Version: 3.0.4 LATEST
Scenario: It seems to have a problem when a couple of editors are loaded in a single component. I tried to get rid of the last one editor and then it works well.

![image](https://user-images.githubusercontent.com/3799158/62440111-946bb500-b789-11e9-8635-3ff2c3773201.png)

**Comment by casualuser** [comment]
Hi
We saw such issues when `setState` was called in cycle inside `componentDidUpdate`
You can find this working samples with multiple editors enabled
https://codesandbox.io/s/pbuiv
https://stackblitz.com/edit/react-u1pduv
