### ISSUE TITLE
The value does not change in version 3.0.4

### ISSUE THREAD

**Issue by philipseo** [froala/react-froala-wysiwyg#186]
<img width="597" alt="스크린샷 2019-08-06 오전 11 32 27" src="https://user-images.githubusercontent.com/6640453/62507058-f84fb580-b83d-11e9-9883-cde139de8288.png">

Normal operation was confirmed in version 3.0.3.
However, as shown in the screenshot, confirmed that the value of the textarea tag was not binded.
What should I do?

**Comment by dominikdosoudil** [comment]
I've noticed same problem. I think that #191 solves it. At least it seems to work for me.
