### ISSUE TITLE
TributeJS doesn't work with react-froala-wysiwyg

### ISSUE THREAD

**Issue by abdullahtariq1171** [froala/react-froala-wysiwyg#189]
TributeJS example doesn't work in `react-froala-wysiwyg` but works when using directly `FroalaEditor` without react package.

Here is example using react package which throws error of `editor.events` undefined in initialized callback
https://codesandbox.io/s/serverless-rain-egzvi

this works without using react-froala-wysisyg https://jsfiddle.net/uzjb23gh/1/ so my guess is the issue is with this package.

---
"react-froala-wysiwyg": "^3.0.4",
"froala-editor": "^3.0.4",

**Comment by freenetbrasil** [comment]
Same thing here, trying to get it working without success!

**Comment by gregoryforel** [comment]
Hey guys, check [that](https://codesandbox.io/s/froala-react-xrqvj) out

**Comment by abdullahtariq1171** [comment]
@gregoryforel nope this doesn't work. try using it with keyboard only (without cursor).

**Comment by gregoryforel** [comment]
@abdullahtariq1171 you just have to add `import 'tributejs/dist/tribute.css'`

**Comment by abdullahtariq1171** [comment]
nope, See https://monosnap.com/file/fh4exRZgpozQQrKgpQ3HEEt3cRiYyt, It works fine when we add it using cursor click, but when we try using keyboard (Pressing Enter) it doesn't add the tributejs tag, instead treat it as normal enter (which it to move to next line).

Now, to solve this problem we need to register an event when froala is initiated, see [froala docs](https://www.froala.com/wysiwyg-editor/examples/tribute-js) which is where we're facing this error.

**Comment by gregoryforel** [comment]
Have you opened my link at all? It works.

**Comment by abdullahtariq1171** [comment]
> Have you opened my link at all? It works.

Yes, I did. You can also see I'm using your shared link in above shared screencast. 

I even looked into code, seems like you don't register any event at all. Which is exactly where it throws this error. 

There are [other people](https://github.com/froala/react-froala-wysiwyg/issues/184#issuecomment-519341513) who're facing the same issue

---

> I give up lol. Maybe the guys from Froala answer. Good luck

thanks for trying

**Comment by mrfambo** [comment]
@abdullahtariq1171 After heck of ups and downs, i gave up too.
(Bakwas editor hey, aur koi option hi nh mill rha seriously)

**Comment by abdullahtariq1171** [comment]
Okay I downgraded to 3.0.3 and it works for now, but 3.0.4 have this issue.

**Comment by gregoryforel** [comment]
That's great, thanks for the feedback!

**Comment by brianarpie** [comment]
I can confirm this works for 3.0.3

**Comment by brianarpie** [comment]
I just updated to 3.0.5 and tributejs is still working for me. I posted in this other ticket to show the pattern I'm using to attach tribute. https://github.com/froala/react-froala-wysiwyg/issues/184#issuecomment-530452825

**Comment by dejanmartinovic** [comment]
I think I've managed to implement Tribute.js in react-froala.
Check this example: https://codesandbox.io/s/lively-breeze-l9z82

**Comment by vladpavlovski** [comment]
@dejanmartinovic Thank you for solution, works well with 3.0.6 class or functional component

**Comment by rizalrhmn** [comment]
it works on 3.2.3. But i'm a bit annoyed with using "this" on my functional component that has fully using React Hooks. Did anybody know how to do this with React Hooks? I've tried using UseEffect and UseRef but it seems not quite stable (there was some racing), sometimes I got those "editor.html.set undefined" error.

**Comment by ilyaskarim** [comment]
Reference to working demo: https://github.com/froala/react-froala-wysiwyg/issues/189#issuecomment-535440237
