### ISSUE TITLE
custom Plugin doesn't work

### ISSUE THREAD

**Issue by danielbentov** [froala/react-froala-wysiwyg#19]
We added a custom plugin while working with Plain js froala files.
It worked great.
You can see it here: (Add Personalization)
![image](https://cloud.githubusercontent.com/assets/8301213/23652320/1a3445f4-0331-11e7-8a44-3bff794e0150.png)

We are now using React & Redux. So we are using the react-froala-wysiwyg but it doesen't initiate new plugins. It only initiate the built in plugins in the node modules.
![image](https://cloud.githubusercontent.com/assets/8301213/23652021/0a53ba76-0330-11e7-808a-913eb3a1b246.png)
![image](https://cloud.githubusercontent.com/assets/8301213/23652030/115a36ec-0330-11e7-8145-ca42bbfc7b11.png)

The editor works but you won't see any custom plugin and the it code doesn't run.
![image](https://cloud.githubusercontent.com/assets/8301213/23652064/305c845a-0330-11e7-8eea-169be259189b.png)

**Comment by KevinGorjan** [comment]
How did you solved it?
Having the same problem here...

**Comment by stefanneculai** [comment]
@KevinGorjan you'd have to include it just after the editor JS files: 
```js
import 'froala-editor/js/froala_editor.pkgd.min.js';
```
