### ISSUE TITLE
html error

### ISSUE THREAD

**Issue by rojer95** [froala/react-froala-wysiwyg#20]
click html toolbar buttom 

there is error message:

> 
> Uncaught TypeError: l.setSize is not a function
>     at f (froala_editor.pkgd.min.js:14)
>     at Object.g [as toggle] (froala_editor.pkgd.min.js:14)
>     at b.callback (froala_editor.pkgd.min.js:14)
>     at Object.d [as exec] (froala_editor.pkgd.min.js:10)
>     at f (froala_editor.pkgd.min.js:11)
>     at g (froala_editor.pkgd.min.js:11)
>     at h (froala_editor.pkgd.min.js:11)
>     at b.i (froala_editor.pkgd.min.js:11)
>     at m (froala_editor.pkgd.min.js:7)
>     at HTMLButtonElement.eval (froala_editor.pkgd.min.js:7)

**Comment by stefanneculai** [comment]
@rojer95 could you please send us a link where we can reproduce it? Thank you.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
