### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by sermicromegas** [froala/react-froala-wysiwyg#209]
When I try to add this option:

```
events : {
        'initialized' : function() {
            console.log(this)
        }
    }

```
I get the error on file index.js:227 ( this.editor.events.on("contentChanged", function () { )

Version 3.0.6 both react-froala-wysiwyg and froala-editor.

Thank you.

**Comment by asandhu3** [comment]
@sermicromegas What was the issue?

**Comment by sermicromegas** [comment]
> @sermicromegas What was the issue?

I had multiple instances of the editor and a global editor config object.
I passed the config to the editors using config={{...editorConfig]} but this made a shallow copy.
I had to use config={_.cloneDeep(editorConfig)} (using lodash).

**Comment by asandhu3** [comment]
Thank you!
