### ISSUE TITLE
Change Events in Code View

### ISSUE THREAD

**Issue by EricFries** [froala/react-froala-wysiwyg#21]
Is `onModelChange` supposed to fire on key strokes when inside the code view?  

The event isn't firing for me until the code view is closed.  I'm curious if this is intended because the difference in behavior between the code view and regular view is making updating a parent component's state a little tricky.

I'm using v2.5.1.

**Comment by stefanneculai** [comment]
This is by design. Please find more about this in the following discussion: https://github.com/froala/wysiwyg-editor/issues/1465#issuecomment-248594297.
