### ISSUE TITLE
Error Rendering inside React Storybook

### ISSUE THREAD

**Issue by liorpr** [froala/react-froala-wysiwyg#22]
I'm trying to render the editor inside a story and I get this error

![screen shot 2017-04-12 at 11 06 40](https://cloud.githubusercontent.com/assets/6891569/24947732/8dec07c4-1f70-11e7-8ed5-61847c706088.png)

**Comment by stefanneculai** [comment]
@liorpr could you put together a demo where we can check it? Thanks.

**Comment by liorpr** [comment]
here are some more details:
`
 plugins = [
    'fontSize',
    'fontFamily',
    'paragraphFormat',
    'align',
    'lists',
    'link',
    'image',
    'table',
  ];

 toolbarButtons = [
    'bold',
    'italic',
    'underline',
    'fontSize',
    'fontFamily',
    '|',
    'paragraphFormat',
    'align',
    'formatOL',
    'formatUL',
    'indent',
    'outdent',
    'table',
  ];
`

**Comment by stefanneculai** [comment]
@liorpr that is not really enough details to reproduce it. It looks like somehow the editor instance is being destroyed before it's initialized or something like this. Unfortunately, we cannot help without seeing all the code you have there in place.
