### ISSUE TITLE
React Package Breaks entire app 

### ISSUE THREAD

**Issue by GaddMaster** [froala/react-froala-wysiwyg#224]
When I add this simple file anywhere it breaks the entire app

```
import React from "react";
import ReactFroalaEditor from "react-froala-wysiwyg";
class TestEditor extends React.Component {
  render () {
    return (
      <div>
        <ReactFroalaEditor tag = "textarea" />
      </div>
    );
  };
};
export default TestEditor;
```

It only breaks on live app, not locally.

If I remove the Froala import its fine.

Error -> 
index.js:98 Uncaught TypeError: Super expression must either be null or a function, not undefined

Can you help me, please 

Daniel

**Comment by mrfambo** [comment]
Did you tried downgrading?

**Comment by GaddMaster** [comment]
I am not sure what happened. I think i just started from scratch and worked way back up to working app. I do believe it was some new package versions had conflicts. Cannot remember which ones, but package version conflicts was a new lesson

**Comment by mikecsmith** [comment]
I've just hit this issue on a Sharepoint SPFx project - trying to debug now and will attempt a downgrade

**Comment by GaddMaster** [comment]
@mikecsmith Best of luck. My last comment still stands !

**Comment by mikecsmith** [comment]
Thanks @GaddMaster - managed to get it working by turning off the mangle/minification process in SPFx's webpack setup. Turns out it was also breaking React Table. Has increased bundle size significantly but I can probably build my own custom minification process in - once I figure out how to use their custom webpack/gulp hybrid process better.

My advice - stay away from Sharepoint development unless there's no other work available :)

**Comment by m-andrew-albright** [comment]
My team is seeing this until we downgraded to 3.0.6 -- Froala Team, please get on this so we can use some of the improvements that have been made, like copy/paste from Word!

**Comment by burnhamrobertp** [comment]
We ran into this as well, though I'm not sure how I didn't find this issue until now. Disabling uglification/minifying is not a viable solution and because this bug seems to exist in the closed-source version of the Froala library, we can't even fork and fix it ourselves. In many ways the 3.0.6 version of copy/paste handling is far worse than what we had before we even upgraded out of the 2.x line that we were in previously!

**Comment by making3** [comment]
Happening for me as well. When running this locally without minification, it's not a problem, but when we deployed it to our server, it blew up.

If you enable `keep_fnames: true` in the minimizer config in the react-froala-wysiwyg repo and build, the issue goes away (this isn't sustainable, of course).

Example:
```
    optimization: {
        minimizer: [
            new TerserPlugin({
                terserOptions: {
                    keep_fnames: true,
                },
            }),
        ],
    },
```

**Comment by mstangret** [comment]
Still occuring in 3.2.1-1

**Comment by chetan-bura-cuelogic** [comment]
Same issue I am getting for version `3.2.1-1`
`Uncaught TypeError: Super expression must either be null or a function, not undefined   index.js:114`

**Comment by chetan-bura-cuelogic** [comment]
I am getting an issue with `edit.off()` and `edit.on()`, I can able to edit on the editor when I have done `edit.off()` on version `3.2.1-1` and I have tried the same thing on version `3.0.6` its working fine.

**Comment by EspadaV8** [comment]
Any updates on getting a fix for this?

**Comment by runabh** [comment]
Still seeing this issue on v3.2.6-1
Any updates on getting a fix?

**Comment by arunkumaryoyo** [comment]
Team, any update on fixing this issue? We are planning to procure a license and this is a blocker now.

**Comment by challet** [comment]
Any progress on this ? That's a blocker for using react-froala-wysiwyg.

**Comment by nikhil-ponduri** [comment]
We have faced similar problem and we solved this issue by adding froala in webpack excludes
```
 exclude: /node_modules[\/\\](?!(swiper|dom7|@jimp\/core|d3-array|d3-scale|file-type|react-wordcloud|striptags|froala-editor|react-froala-wysiwyg)[\/\\])/
```
this is how our webpack excludes look like and this solved our problem

As an enhacement we took one more step and we served froala as CDN package


Hope this works for you guys

**Comment by jordanhudgens** [comment]
We just paid $1k for the pro version and can't even deploy it because of this issue, is this going to be addressed?

**Comment by ravindreramjiawan** [comment]
Upgrading webpack 4 to the highest vesion resolved the issue for me.
`"webpack": "4.8.3", -> "webpack": "4.46.0"`

**Comment by Rahulgarg30591** [comment]
Hello, @GaddMaster this is now resolved in React Froala's latest version. The babel packages were deprecated of the package, which is now [fixed](https://github.com/froala/react-froala-wysiwyg/pull/280).
The same is tested with the CRA prod build and deployment.

**Comment by ilyaskarim** [comment]
Fixed in https://github.com/froala/react-froala-wysiwyg/pull/280
