### ISSUE TITLE
highlight what size font the current text is?

### ISSUE THREAD

**Issue by sureshreddysolipuran** [froala/react-froala-wysiwyg#236]
Hi Froala team,

I looking for following option
"highlight what size font the current text is?"

![Screenshot (253)](https://user-images.githubusercontent.com/36910187/78783603-8b3e8200-79c1-11ea-9d13-469bd8d947a5.png)

**Comment by dejanmartinovic** [comment]
@sureshreddysolipuran Can you confirm that issue is still reproducible?
https://jsfiddle.net/dejan_m/og0hxf2t/4171/
