### ISSUE TITLE
Update to ES6 classes

### ISSUE THREAD

**Issue by MichaelDeBoey** [froala/react-froala-wysiwyg#25]
Like discussed in [#24](https://github.com/froala/react-froala-wysiwyg/pull/24#issuecomment-295240359): instead of using the `create-react-class` package, use proper ES6 classes (as [recommended](https://facebook.github.io/react/docs/components-and-props.html#functional-and-class-components) by the React-team).

CC: @stefanneculai

**Comment by MichaelDeBoey** [comment]
+1 Bump

**Comment by MichaelDeBoey** [comment]
@stefanneculai Any news on this one?

**Comment by stefanneculai** [comment]
@MichaelDeBoey there should be an update next week most likely.

**Comment by MichaelDeBoey** [comment]
@stefanneculai Any news on this one? 🙂

**Comment by stefanneculai** [comment]
@MichaelDeBoey could please you give a try to https://github.com/froala/react-froala-wysiwyg/pull/28?

**Comment by MichaelDeBoey** [comment]
@stefanneculai I've added some suggestions 🙂

**Comment by stefanneculai** [comment]
Thanks a lot! We're going to update it in the following days.
