### ISSUE TITLE
React Deprecation Warning

### ISSUE THREAD

**Issue by christofflueck** [froala/react-froala-wysiwyg#251]
When running Froala I receive the following warning in the console:

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder

This is when using React v16.13.1

**Comment by NathanCH** [comment]
Which version are you using? See if upgrading `react-froala-wysiwyg` to `3.2.0` fixes it.

**Comment by christofflueck** [comment]
Yes release 3.2.0 fixed the issue. Thanks @NathanCH
