### ISSUE TITLE
Every editor instance created makes new web requests for assets loaded by previous instance

### ISSUE THREAD

**Issue by colwynmyself** [froala/react-froala-wysiwyg#26]
I have a page I'm building that can have hundreds of instances of the Froala editor on it on page load. The issue is every time a new editor is loaded on a page it makes requests to these URLs:

- https://dme0ih8comzn4.cloudfront.net/imaging/v3/editor.js
- https://demo.webspellchecker.net/froala/customscayt.js
- http://feather.aviary.com/csdk/4.3.1.35/css/feather_core_minimum.css
- http://feather.aviary.com/csdk/4.3.1.35/js/feathercontrols_en.js
- https://svc.webspellchecker.net/spellcheck/script/ssrv.cgi (banner request)
- https://svc.webspellchecker.net/spellcheck/script/ssrv.cgi (lang_list request)
- https://demo.webspellchecker.net/froala/local/en/local.js

This slows the page down substantially and can take multiple minutes to load. Is there a way around this? This is the component we're using it in right now. It's included on various pages around the application and as I mentioned can be included up to 100 times.

```
import React from 'react'
import FroalaEditor from 'react-froala-wysiwyg'

class RichText extends React.Component {
    constructor(props) {
        super(props)

        const buttons = ['fullscreen', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', 'fontFamily', 'fontSize',
            '|', 'color', 'inlineStyle', 'paragraphStyle',
            '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'insertHR',
            '|', 'undo', 'redo', 'clearFormatting', 'selectAll',
            '|', 'insertTable', 'tableRemove',
            '|', 'tableRows', 'tableColumns', 'tableStyle',
            '|', 'tableCells', 'tableCellBackground', 'tableCellVerticalAlign', 'tableCellHorizontalAlign', 'tableCellStyle',
            '|', 'insertFile', 'insertImage', 'insertLink', 'insertVideo']

        this.state = {
            options: {
                placeholderText: this.placeholder || '',
                toolbarButtons: props.buttons || buttons,
                toolbarButtonsMD: props.buttons || buttons,
                toolbarButtonsSM: props.buttons || buttons,
                toolbarButtonsXS: props.buttons || buttons,
                tabSpaces: false,
                key: 'redacted',
                // Image uploading params
                imagePaste: true,
                imageUploadParam: 'file',
                imageUploadParams: {
                    studyId: props.studyId,
                    froala: true,
                },
                imageUploadURL: '/api/file-upload',
                imageUploadMethod: 'POST',
                imageMaxSize: 10 * 1024 * 1024, // 10MB
                // File uploading params
                fileUploadParam: 'file',
                fileUploadParams: {
                    froala: true,
                },
                fileUploadURL: '/api/file-upload',
                fileUploadMethod: 'POST',
                fileMaxSize: 10 * 1024 * 1024, // 10MB
                events: {
                    'froalaEditor.focus': () => {
                        this.setEditing(true)
                    },
                    'froalaEditor.blur': (e, editor) => {
                        props.onChange(editor.html.get())
                        this.setEditing(false)
                    },
                },
            },
        }

        this.setEditing = state => {
            this.setState({ editing: state })
        }
    }
    render() {
        return (<div className={`input-field rich ${this.state.editing ? 'editing' : ''}`}>
            <FroalaEditor config={this.state.options} model={this.props.value} />
        </div>)
    }
}

export default RichText
```

My inclination is there isn't an easy workaround for this as the code in this repo directly calls on the froala-editor node module. It would be awesome if there were a way for the component to know that it already loaded those assets and that it doesn't need to make a new request.

**Comment by stefanneculai** [comment]
We're aware of this and there ahould be an update in less than a week. In the meanwhile, as a workaround, do not include the spellChecker plugin,

**Comment by colwynmyself** [comment]
Oh awesome, thanks for the quick response! I'll do that, thank you. I'll leave this open just in case y'all wanna leave it until you push the fix or just wanna close it now. Cheers!

**Comment by colwynmyself** [comment]
What options do I set to disabled that plugin? I've set these two in the `this.state.options` object but it's still loading all those assets
```
this.state = {
    options: {
        spellcheck: false, 
        scaytAutoload: false,
        ...
```

**Comment by stefanneculai** [comment]
You could use the pluginsEnabled option or not include it at all (the js files for it).

**Comment by colwynmyself** [comment]
Oh duh, alright awesome. That's working for me. Thank you very much!
