### ISSUE TITLE
Minified React Gives Error

### ISSUE THREAD

**Issue by ravindreramjiawan** [froala/react-froala-wysiwyg#289]
With the latest release 3.2.6-1 when react is minified it gives an error.

https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=TypeError%3A%20Super%20expression%20must%20either%20be%20null%20or%20a%20function%2C%20not%20undefined&args[]=(url)

**Comment by challet** [comment]
Looks like a duplicate of #224 which is awaiting a fix for more than a year
