### ISSUE TITLE
is it possible to parse customized callback response

### ISSUE THREAD

**Issue by git4sun** [froala/react-froala-wysiwyg#30]
is it possible to parse customized callback response? Because the cloud image service I used to upload image doesn't return the same format as described in froala docs. Actually it doesn't even return json, it returns XML. Is it possible to parse it by myself and pass the result to froala? What could I do to support customized callback response.

**Comment by stefanneculai** [comment]
Sure, you could use the `image.uploaded` event and inside that return false to stop the default upload chain and process the response on your own.
