### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto' 

### ISSUE THREAD

**Issue by Julian-B90** [froala/react-froala-wysiwyg#318]
I have use CRA (create-react-app). 

react-scripts Version 5.0.0

Error Message:
```
WARNING in ./node_modules/froala-editor/js/plugins.pkgd.min.js 7714:12-29
Module not found: Error: Can't resolve 'crypto' in '/Users/julian/projects/halloProject/node_modules/froala-editor/js'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```

**Comment by paekhunseo** [comment]
The tailwind is not being updated 
because the froala-react does not support the react-scripts Version 5.0.0.
It's been a while since the react-scripts Version 5.0.0 came out.

**Comment by nirvparekh** [comment]
Facing the same issue

**Comment by paekhunseo** [comment]
1. node_modules > react-scripts > config > webpack.config.js  -->  305 line 
   Fix it as below.

![image](https://user-images.githubusercontent.com/42810776/170448736-de51eb5f-2c2c-40fa-871f-edca5159fe53.png)

3. npm i -D https-browserify buffer crypto-browserify os-browserify stream-browserify stream-http

![image](https://user-images.githubusercontent.com/42810776/170449004-d2ef32b0-f203-46f7-9747-d1ed1c5dc520.png)

This temporary way will eliminate the message.

**Comment by MateuszStawski** [comment]
> 1. node_modules > react-scripts > config > webpack.config.js  -->  305 line
>    Fix it as below.
> 
> ![image](https://user-images.githubusercontent.com/42810776/170448736-de51eb5f-2c2c-40fa-871f-edca5159fe53.png)
> 
> 3. npm i -D https-browserify buffer crypto-browserify os-browserify stream-browserify stream-http url assert
> 
> ![image](https://user-images.githubusercontent.com/42810776/170449004-d2ef32b0-f203-46f7-9747-d1ed1c5dc520.png)
> 
> This temporary way will eliminate the message. another compile error is removed by including GENERATE_SOURCEMAP=false
> 
> cross-env **GENERATE_SOURCEMAP=false** react-scripts start

how can editing node modules file be a solution? once reinstalling npm it is all gone

**Comment by kitsanapong** [comment]
I solved this by webpack configuration via cargo.config.js

```
webpack: {
    configure: (webpackConfig) => {
      webpackConfig.resolve.fallback = {
        crypto: require.resolve('crypto-js')
      }
      return webpackConfig
    },
}
```

Note:
```
webpack: {
    resolve: {
      fallback: {
        crypto: require.resolve('crypto-js'),
      },
    },
}
```
webpack.fallback should work but it did not for my case. Then I tried webpack.configure and it worked
