### ISSUE TITLE
Support wiris plugin

### ISSUE THREAD

**Issue by francescobarbera** [froala/react-froala-wysiwyg#32]
I have some problems installing wiris plugin
as described [here](http://www.wiris.com/plugins/docs/froala) at the point number 4, you have to include wiris.js.

This file looks for $.FroalaEditor object, for example $.FroalaEditor.DEFAULTS, but $.FroalaEditor is always empty.

I think that the problem is that with frolla react component jQuery is only used to build internal component layout, and not to manage all the component from outside. 

Does some one else have a problem like this?

**Comment by stefanneculai** [comment]
@francescobarbera the Wiris integration is maintained by the Wiris team. Please contact them for help on integrating it: http://www.wiris.com/en/contact. Thanks.

**Comment by atouzel** [comment]
@francescobarbera have you fixed this? I'm having the same problem. Did the Wiris team helped you with that?
