### ISSUE TITLE
Froala rendering twice when using React.StrictMode

### ISSUE THREAD

**Issue by BickelLukas** [froala/react-froala-wysiwyg#329]
**Problem:**
When wrapping the app in `<React.StrictMode>` the editor ist rendered twice.
<img width="336" alt="image" src="https://user-images.githubusercontent.com/16354178/167627015-1a6a8132-9b90-484f-bbf2-b041451e1478.png">

**Version:**
"react": "^18.0.0",
"froala-editor": "^4.0.11",
"react-froala-wysiwyg": "^4.0.11",

**Comment by enayaaat** [comment]
same issue.

**Comment by aayush301** [comment]
Same issue

**Comment by ffaubert** [comment]
As a paying customer, it is very disappointing how poorly maintained the react bindings are. React 18 has been out for a long time, as has webpack 5. I can't in good faith add a dependency on our product that is so poorly maintained...

**Comment by Deep1Shikha** [comment]
Could you share a fiddle, sandbox link with the problem that you are facing?

**Comment by hyochan** [comment]
> As a paying customer, it is very disappointing how poorly maintained the react bindings are. React 18 has been out for a long time, as has webpack 5. I can't in good faith add a dependency on our product that is so poorly maintained...

So what are the alternative you think would be better?

**Comment by hyochan** [comment]
```
import FroalaEditorFunctionality from './FroalaEditorFunctionality.jsx';
import React from 'react';

export default class FroalaEditor extends FroalaEditorFunctionality {
+  componentDidUpdate(prevProps) {
+    if (this.element.style.display === 'none') {
+      this.destroyEditor();
+      return;
+    }
+  }

  render () {
    return <this.tag ref={el => this.el = el}>{this.props.children}</this.tag>;
  }

```
I tried to solve the issue on my side but quite complicated to know what's going on internally.
`destroyEditor` changes to `display` style to `none` but it is actually gone.

Hopefully, will come back later if I find more clues.

**Comment by jovana** [comment]
Yes, please! A fix would be very appreciated!!

**Comment by gracefullight** [comment]
Good news here.

> We are glad to inform you that development has scheduled a fix for this issue and it will be in the next product release V4.0.16. Please subscribe to https://www.froala.com/wysiwyg-editor/download#updates to see the latest updates on new releases.

**Comment by eirikedh** [comment]
Updating to V4.0.16 did not work for me, and I dont see anything written about it in the changelog.

**Comment by ilyaskarim** [comment]
Considering the significant amount of changes that need to be done to fully support React 18 and a cross-team QA effort is required, The integration is scheduled for V4.1. 
In the meantime, The issue can be easily mitigated by using React's useEffect Hook:  https://codesandbox.io/s/pedantic-water-4gl563.

**Comment by marvinIsSacul** [comment]
Still nothing?

The above solution using React's useEffect doesn't seem to do the trick.

> Considering the significant amount of changes that need to be done to fully support React 18 and a cross-team QA effort is required, The integration is scheduled for V4.1. In the meantime, The issue can be easily mitigated by using React's useEffect Hook: https://codesandbox.io/s/pedantic-water-4gl563.

**Comment by gracefullight** [comment]
Not sure when version 4.1 will be released. Did you have plans to provide the original source for paying customers to resolve issues directly? @ilyaskarim

**Comment by Maadtin** [comment]
Is there any news on this?

**Comment by bordo** [comment]
`useEffect` didn't work form my setup. I went with `lodash/once` as a workaround for this issue.

```javascript
import once from 'lodash/once'

const Editor = () => {
  const initializeOnce = once(({ initialize }) => initialize())
 
  return <FroalaEditor onManualControllerReady={initializeOnce} />
}
```

**Comment by ilyaskarim** [comment]
Fixed in https://froala.com/wysiwyg-editor/changelog/#4.1.0
