### ISSUE TITLE
Direct way to use @mentions in Froala editor

### ISSUE THREAD

**Issue by decpk** [froala/react-froala-wysiwyg#335]
Hi Team,

I'm looking for a way to add mentions like if someone add @ then a dropdown will appear. Do we have any way to do that. I Froala docs I'm not able to find it. I'm specially looking for a way in react.

**Comment by iamkimani-ndegwa** [comment]
Hey @decpk. You can use tribute JS. It is the most direct way IMO. Here is an example in the [docs](https://froala.com/wysiwyg-editor/examples/tribute-js/) and an example using [React JS](https://codesandbox.io/s/xrqvj)
