### ISSUE TITLE
Froala doesn't focus when `initOnClick` is set

### ISSUE THREAD

**Issue by MrToph** [froala/react-froala-wysiwyg#34]
Hi,

when I use the `FroalaEditor` in addition with the `initOnClick` property, the first click initializes Froala, but then the component is not focused and no cursor appears at the place in the text I clicked on.

After initialization, clicking works fine. So with the `initOnClick` property this component requires a second click to actually select the text.

It looks like [this issue from the ember version](https://github.com/froala/ember-froala-editor/issues/27) of _froala_ also happens in the React version.

**Comment by stefanneculai** [comment]
@MrToph Thanks for letting us know about it. We'll look into it.

**Comment by MrToph** [comment]
@stefanneculai Short update: I looked into it and it indeed has to do with the `html.set` that happens in the initialization event when `firstTime` is true. If I [comment that line](https://github.com/froala/react-froala-wysiwyg/blob/master/lib/FroalaEditorFunctionality.jsx#L112), it works fine.

**Comment by stefanneculai** [comment]
Thanks for the additional check, @MrToph. We're going to fix it shortly.

**Comment by raphaelbeckmann** [comment]
When will this be fixed? As I understand the solution already has been communicated.

**Comment by MrToph** [comment]
I fixed it, see my Pull Request #43

**Comment by raphaelbeckmann** [comment]
For desktop browsers it seems to be fixed.
But on mobile devices the focus is not being set, thus the keyboard does not show up when tapping on the textarea. We always have to tap twice.

**Comment by stefanneculai** [comment]
@raphaelbeckmann are you experiencing that here as well: https://www.froala.com/wysiwyg-editor/examples/init-on-click?

**Comment by dansackett** [comment]
It looks like the pull request fixing this issue has not been merged yet. Was there further work needing to be done or will this be included in an upcoming release?

**Comment by topher515** [comment]
+1 Would like #43 merged, please.

**Comment by stefanneculai** [comment]
#43 merged.
