### ISSUE TITLE
Cannot set property 'froalaEditor' of undefined

### ISSUE THREAD

**Issue by Denly** [froala/react-froala-wysiwyg#35]
TypeError: Cannot set property 'froalaEditor' of undefined
(anonymous function) node_modules/froala-editor/js/froala_editor.pkgd.min.js:7

![screen shot 2017-07-31 at 1 02 31 pm](https://user-images.githubusercontent.com/7588279/28791320-0e4f7e48-75fa-11e7-93a9-42817636f279.png)

Can't fix it. Hope to get some support. Thank you! 
index.js

```
// Require Editor JS files.
import 'froala-editor/js/froala_editor.pkgd.min.js';

// Require Editor CSS files.
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

// Require Font Awesome.
import 'font-awesome/css/font-awesome.css';

```
webpack setting

```
module: {
    strictExportPresence: true,
    rules: [
      // my loader to expose jquery to global
      {
        test: require.resolve('jquery'),
        use: [{
          loader: 'expose-loader',
          options: '$'
        }]
      },...

new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      'window.jQuery': "jquery",
      'window.$': "jquery",....
```

**Comment by stefanneculai** [comment]
@Denly it looks like jQuery is not defined globally. If jQuery is correctly defined globally, you should be able to see in developer console the following object: `$.FroalaEditor`.

**Comment by Aaronik** [comment]
I had a similar problem that persisted past whatever I did trying to get jquery into the fold. So I tried busting out the demo, and lo and behold, the same problem was happening. My company uses node v4.4.x (ancient now, I know), which is what I have as the default on my system now. I tried using v6.9.0, and :boom:, it worked like a charm. Not sure if this is the only way to fix it (and dearly, dearly hoping it isn't), but I thought I'd share here.

**Comment by PhilAndrew** [comment]
@Denly did you manage to fix this problem? How can I use Froala in Nuxt.js?

**Comment by stadja** [comment]
So yes, did you fixed this problem ?

**Comment by stadja** [comment]
For me, to fix this in Angular (my problem was that in server side rendering it was failing), I just added at the begining of **froala_editor.pkgd.min.js**

`  if (typeof window == 'undefined') {
    return;
  }`

**Comment by clodal** [comment]
Fiddled with this for a long while and came up with this that works with SSR

```
import React from 'react'
import PropTypes from 'prop-types'
import 'froala-editor/css/froala_style.min.css'
import 'froala-editor/css/froala_editor.pkgd.min.css'
import 'font-awesome/css/font-awesome.css'

/**
 * Fix issues with SSR
 * (Require Editor JS files)
 * @link https://github.com/froala/react-froala-wysiwyg/issues/35
 */
let FroalaEditor
if (typeof window !== 'undefined') {
  /* eslint-disable global-require */
  require('froala-editor/js/froala_editor.pkgd.min')
  FroalaEditor = require('react-froala-wysiwyg').default
  /* eslint-enable global-require */
}

class Editor extends React.Component {...}

export default Editor
```
