### ISSUE TITLE
'iframe' mode editor crashed when destroy before it is not fully initialized

### ISSUE THREAD

**Issue by torrac12** [froala/react-froala-wysiwyg#353]
We found editor crashed in our product if the editor frequently init and destroy,  and we simplify the bug to below demo

Please see: https://codesandbox.io/s/billowing-paper-pn1fe5?file=/src/App.js.

It only happens in "iframe" mode,  seems the editor get destroy before it fully initialized which cause the issue

**Comment by ilyaskarim** [comment]
By properly waiting for the asynchronous operations to complete before setting showEditor to true, this error should be resolved.
Please take a look at this updated demo: https://codesandbox.io/s/jovial-curie-2qcnn3?file=/src/App.js.
