### ISSUE TITLE
Cannot cancel Events (like keyup, keydown) etc

### ISSUE THREAD

**Issue by evilsoft** [froala/react-froala-wysiwyg#37]
Was trying to implement a really neat flow that would add a new item when a user strikes the Enter key. Much to my chagrin, after setting up the events and creating a, quite stellar I might add, event handler for `froalaEditor.keydown` it appears no matter where or how I stop propagation and cancel default I cannot keep the event from doing what it does.

After jumping through some code, I think I tracked it down to how events are registered [here](https://github.com/froala/react-froala-wysiwyg/blob/1472da6334c399d6071bb73d220208958a11a4e8/lib/FroalaEditorFunctionality.jsx#L242). It looks like there is a handy third argument that takes a Boolean that dictates if a given event should fire before all other registered events.

Have you or any other users ran into this before?

**Comment by evilsoft** [comment]
Well nope, that is a wild goose chase, but I still think it may be an issue of the order in which events are bound.

**Comment by evilsoft** [comment]
You know what I am so sorry. Let me get a work around working in my project and once I get that working I will post an example to highlight the 🐞. Sorry about the drive-by. Will post something.

**Comment by stefanneculai** [comment]
@evilsoft that is happening most likely because the editor is preventing the event to go further. The best thing would be to bind to the keydown event inside the initialized event, similar to the drop example from our website: https://www.froala.com/wysiwyg-editor/examples/drop-content.

**Comment by evilsoft** [comment]
That is exactly what I did to get around it. Perfect!
Thanks a tonne

**Comment by zivlevy** [comment]
How can I stop enter event from bubbling up? I can catch the event but the default addition of P is still happening regardless of stopPropagation  and stopImmediatePropagation

**Comment by namti** [comment]
This solves it
#https://github.com/froala/wysiwyg-editor/issues/2579#issuecomment-369618500
