### ISSUE TITLE
How to use customize  froalaEditor.image.uploaded?

### ISSUE THREAD

**Issue by DWYW** [froala/react-froala-wysiwyg#38]
froala_editor v2.6.5

``` javascipt 
events: {
  'froalaEditor.image.uploaded': (e, editor, response) => {
    response = JSON.parse(response);
    if(response.code == 0) {
      editor.image.insert(response.data.urls.base);
      return false
    }
}
```

result: 
![image](https://user-images.githubusercontent.com/19439805/30411755-ac39665a-9945-11e7-854a-fc6e89f76d34.png)

![image](https://user-images.githubusercontent.com/19439805/30411785-db0e2efc-9945-11e7-99fc-161483edd699.png)

The result is double image?

**Comment by DWYW** [comment]
I solved it.
use editor.image.insert(response.data.urls.base, true, null, editor.image.get(), null) in uploaded.

**Comment by mattb1981** [comment]
Using: 2.7.3

Can this be reopened, using the above fixes the issue with double images, but it means that just a br tag is added to the state of the editor (we store the state in redux), e.g.:

            editor.image.insert(imageUrl, true, null, editor.image.get(), null);

Gives this in redux:
```
{
  Editor: {
    editorState"""<p><br></p>"
  }
}
```

Where as using means we get the correct redux state:

            editor.image.insert(imageUrl);

Appears there are two onModalChange events fired:

1.

```
Editor:{
    editorState: null => "<p><br></p>"
}
```

2.

```
Editor: {
    editorState"<p><br></p>""<p><img src=\"http://ourimageurl=\" style=\"width: 300px;\" class=\"fr-fic fr-dib\"><br></p>"
}
```
But leaves us with this on the editor:

![image](https://user-images.githubusercontent.com/33954261/36039163-9cef9686-0db9-11e8-8cc8-d44916d7ce0e.png)

**Comment by stefanneculai** [comment]
@mattb1981 please see https://github.com/froala/wysiwyg-editor/issues/2112#issuecomment-321190805.

**Comment by KhaMinhVLU-2017** [comment]
**hobbesuk**  you can show doc image.insert for me ? please...!
