### ISSUE TITLE
got "TypeError: Cannot call a class as a function" on production mode next.js

### ISSUE THREAD

**Issue by raufmazzidan** [froala/react-froala-wysiwyg#384]
got error below on build mode, (in dev mode is fine)

![image](https://github.com/froala/react-froala-wysiwyg/assets/35219894/4d791fd7-6436-4be9-9f84-8863796585ca)

```
"next": "^13.5.1",
"react-froala-wysiwyg": "^4.1.3",
```

```
const FroalaEditorComponent = dynamic(
  async () => {
    const values = await Promise.all([
      import('react-froala-wysiwyg'),
      import('froala-editor/css/froala_style.min.css'),
      import('froala-editor/css/froala_editor.pkgd.min.css'),
      import('froala-editor/js/plugins.pkgd.min.js'),
      import('froala-editor/js/plugins/image.min.js'),
    ]);
    return values[0];
  },
  {
    loading: () => <Skeleton height={290} />,
    ssr: false,
  },
);
```

```
<FroalaEditorComponent
   config={config}
   model={value}
   onModelChange={onChange}
/>
```

**Comment by mrh2v** [comment]
same error.

**Comment by atobaum** [comment]
I downgraded next.js to 1.14.19.

**Comment by maakcode** [comment]
Open `next.config.js` and try setting **`swcMinify:false`.

I was facing the same error and when I turned off the minification the error went away.
I know turning off the minification isn't a good solution, but it seems to work though.

- https://github.com/vercel/next.js/discussions/57428
- https://nextjs.org/docs/architecture/nextjs-compiler#minification

**Comment by ilyaskarim** [comment]
The issue appears to be related to the Next Js library upgrade, Thanks for pointing out the discussion @maakcode 

The faulty commit can be found here:  https://github.com/vercel/next.js/commit/30da48fcd28b1fc07dcfa06d89b28bec95897d10
