### ISSUE TITLE
unmounting or `destroy`ing editor causes infinite recursion

### ISSUE THREAD

**Issue by topher515** [froala/react-froala-wysiwyg#39]
I'm attempting to incorporate Froala into my project, but when I attempt to unmount my Froala editor (or manually call `destroy` on the controller) I get a "maximum call stack exceeded error".

Like so...
```
Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Z (example.js:21799)
    at Object.remove (example.js:21799)
    at Object.remove (example.js:21799)
    ...
```

Relevant module versions
```
"react-froala-wysiwyg": "2.7.0-1",
"froala-editor": "^2.7.0",
"react": "~15.3.1",
```

My setup seems to be pretty standard, so I'm quite confused:

```
class TextSectionEditor extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      model: props.contentItem ? props.contentItem.renderedCaption : ''
    };

    this.handleModelChange = this.handleModelChange.bind(this);
    this.handleManualController = this.handleManualController.bind(this);
  }

  handleModelChange(model) {
    this.setState({
      model: model
    });
  }

  handleManualController(controller) {
    controller.initialize();
    this.controller = controller;
  }

  componentWillUnmount() {
    if (this.controller) {
      this.controller.destroy(); // Max callstack error
    }
  }

  render() {

    return (
      <div className="section-wrapper section-type-text" >
        <div className="text-wrapper">
          <FroalaEditor
            tag='div'
            config={{}}
            model={this.state.model}
            onModelChange={this.handleModelChange}
            onManualControllerReady={this.handleManualController}
          />
        </div>
      </div>
    );
  }
}
```

Any help would be appreciated.

**Comment by topher515** [comment]
I thought I'd update that we are still encountering this problem on 2.7.5. We have hacked around it by manually remove the Froala Editor node from the DOM like so...

```
import FroalaEditor from 'react-froala-wysiwyg';

class FroalaEditorWithHack extends Component {

  componentWillUnmount() {
    $(this.nodeRef).remove();
  }

  render() {
    return (
      <div ref={(node)=> { this.nodeRef = node; }}>
        <FroalaEditor {...this.props} />
      </div>
    );
  }
}

```

**Comment by dgroh** [comment]
possibliy duplicated of https://github.com/froala/angular-froala-wysiwyg/issues/105

can someone from Froala Team please help on this?

**Comment by topher515** [comment]
Update—the problem is gone! We're now on `react-froala-wysiwyg@2.7.6` and the issue no longer exists (i.e., froala unmounts as expected). Unfortunately I can't confirm 100% that it was the upgrade which fixed the problem, as several other parts of the codebase changed in the same release.

**Comment by dgroh** [comment]
it exists here, we are not using react tho. the toolbar does not close after 10 changes. we are loading the scripts from cdn.

**Comment by stefanneculai** [comment]
This should be fixed in the latest version.
