### ISSUE TITLE
Support require

### ISSUE THREAD

**Issue by dbackeus** [froala/react-froala-wysiwyg#4]
The common way to deal with React packages is to require them as modules. Would be nice to see support for this in this package.

**Comment by dbackeus** [comment]
In fact I was not able to get this to work in our webpack based project even discarding the fact that we don't have proper modules.

For example when `var FroalaEditorFunctionality = { ... }` is included on require it will not actually assign it globally (on `window`) so the objects are not accessible outside the scope of that file itself.

**Comment by BelfordZ** [comment]
would like to use this, but without webpack support as mentioned its a no-go.

**Comment by Inucoder** [comment]
I agree it should be possible to require the files as modules as that is the JS/React standard. I was able to workaround it by copying the code and adding the missing import/export lines to each file. We are building our sources with Gulp + Browserify.

**Comment by stefanneculai** [comment]
Version `2.3.5-1` supports require.
