### ISSUE TITLE
Question about programmatically managing highlighted text using offsets

### ISSUE THREAD

**Issue by Aaronik** [froala/react-froala-wysiwyg#40]
Hello,

I'm looking into bringing Froala into my company's React app. It's all looking great so far, thanks for all the good work! One of the things I need to be able to do is to programmatically highlight a string of text given a start offset and an end offset. These offsets are measured from the beginning of the document, and measure plain characters, not HTML markup tags.

For example, I have a model: "This is my model!". I'm given the offsets `[0, 3]`. I then need to make the word "This" highlight with a colored background.

Is this something Froala can easily manage?

Thanks for the help! And please let me know if there's a better way to get in contact.

**Comment by stefanneculai** [comment]
@Aaronik at this moment we don't have such a feature. The best way to store/restore selection is by using the selection methods from our documentation, together with the selection markers: https://github.com/froala/wysiwyg-editor/issues/803#issuecomment-144942840

**Comment by Aaronik** [comment]
Ok - the selection saving and restoring is a cool feature. However, and I didn't explain this fully above which is my bad, I need to be able to programmatically highlight _multiple strings_ with _different colors_ by using character offsets _at the same time_. I'm having a hard time figuring out how to do this. Any other thoughts? Thanks again for your attention!

**Comment by stefanneculai** [comment]
@Aaronik please contact us via our website for tech support: https://www.froala.com/wysiwyg-editor/contact. Thank you.

**Comment by Muniraj-Mallesh-E6144** [comment]
@Aaronik @stefanneculai Is the above feature supported in the react froala?
