### ISSUE TITLE
Bundle size with create-react-app

### ISSUE THREAD

**Issue by nomadus** [froala/react-froala-wysiwyg#42]
When I analyzed the size of my bundle, it shows that big part of the bundle is taken by froala_editor.pkgd.min.js.  The size is amounted almost 490kb, which is 13% of total size. Is there any way to selectively import components to speed up things?

**Comment by stefanneculai** [comment]
@nomadus the `froala_editor.pkgd.min.js` is include the core JS file `froala_editor.min.js` and [all the editor plugins](https://www.froala.com/wysiwyg-editor/docs/plugins). To reduce the size, I would recommend to include only those plugins that you're using.

**Comment by kewur** [comment]
I have `froala_editor.min.js` and it's 463kb
