### ISSUE TITLE
disable flag won't work

### ISSUE THREAD

**Issue by eldyvoon** [froala/react-froala-wysiwyg#45]
import FroalaEditor from 'react-froala-wysiwyg';

`<FroalaEditor 
     model={model}
      disabled={true}
    />`

Won't work although someone claimed I can disable the input here https://github.com/froala/wysiwyg-editor/issues/242

**Comment by stefanneculai** [comment]
To disable the editor editing, it is best to use the `edit.off` method: https://www.froala.com/wysiwyg-editor/docs/methods#edit.off.
