### ISSUE TITLE
Uploading images to s3

### ISSUE THREAD

**Issue by asadmakram** [froala/react-froala-wysiwyg#48]
Hi,

I am using react-froala-wysiwyg editor in my application. but i am having trouble uploading images on s3 bucket. when i am trying to upload images on the s3; s3 returns error forbidden: 403.

Can anyone share the configuration for uploading image on the s3 for reactjs.

Following is my configuration.

var config = {

 imageUploadToS3: {
        bucket: 'testing-s3upload',
        // Your bucket region.
        region: 'us-east-1',
        keyStart: 'froalaUploads/',
        params: {
          acl: 'public-read', 
          AWSAccessKeyId: 'xxxxxxxxx', 
          AWSSecretAccessKey: 'xxxxxxxxxxxxxxxxxxxx',
          policy: '', // i have no policy applied on my bucket.
          signature: '',
        }
      }
}

<FroalaEditor tag="editor" config={config}/>

**Comment by stefanneculai** [comment]
403 is an error Amazon throws when there is a problem with the permissions set on the bucket.
