### ISSUE TITLE
Unable to scroll after exiting from fullscreen mode

### ISSUE THREAD

**Issue by Inucoder** [froala/react-froala-wysiwyg#5]
Hi, we are using the React integration for Froala Editor 2.3.4 and we found an issue with fullscreen mode.
If the page the editor is mounted in initially has a vertical scroll bar and you go fullscreen and add/remove lines from it so the height of the editor changes, when you exit fullscreen, the vertical scroll of the page dissapears and only shows up again if you make the page component render again, say, by updating it's state.

Steps to reproduce:
1. Mount the FroalaEditor component in a page tall enough so the browser adds a vertical scroll to it.
2. Go fullscreen.
3. Edit the content of the editor by adding/removing lines from it, say, add or remove a text paragraph.
4. Exit fullscreen.
5. The vertical scroll of the page dissapears.
6. The only way for the vertical scroll of the page to show up again is by performing an operation in the UI that makes the page component call render().

Fullscreen mode is an important feature UX wise as the toolbar gets fixed on top and it's available all the time as you write. We were able to workaround it by adding a listener to the 'fullscreen' event where we call forceUpdate() on the page component.

Looks like it has to do with React not being aware of fullscreen mode, as making the page render again solves the issue.

**Comment by stefanneculai** [comment]
@Inucoder this looks more like an editor issue. Are you able to reproduce it outside of your application? Would it be possible to send us a link to a page where to replicate it? Thanks.

**Comment by stefanneculai** [comment]
Closing this due to lack of response.
