### ISSUE TITLE
Drop event handler assigned in config is not called

### ISSUE THREAD

**Issue by wittlesouth** [froala/react-froala-wysiwyg#50]
It appears if you define a drop handler in the configuration file passed to a FroalaEditor object, the drop handler is not called on a drop event. Here is the editor configuration I'm using:

```
    // Define Froala config
    this.FroalaConfig = {
      placeholderText: context.intl.formatMessage(this.componentText.bodyPlaceholder),
      toolbarButtons: [
        'bold', 'italic', 'underline', 'strikeThrough', 'formatBlock', '|',
        'fontFamily', 'fontSize', '|', 'color', 'emoticons', 'align', '|',
        'paragraphFormat', 'formatOL', 'formatUL', 'outdent', 'indent', 'insertTable',
        '|', '|', 'undo', 'redo', 'html'
      ],
      pluginsEnabled: [
        'codeView', 'draggable', 'fontFamily', 'fontSize', 'image', 'link', 'lists',
        'paragraphFormat', 'paragraphStyle', 'table', 'url'],
      events: {
        'froalaEditor.focus': (e, editor) => { console.log('Focus') },
        'froalaEditor.drop': (e, editor) => { console.log('Drop') },
        'froalaEditor.input': (e, editor) => { console.log('Input') }
      },
      key: process.env.FROALA_KEY
    }
```

When I run the page which includes the editor created with this configuration, I see the Focus event being called when the editor gets focus, and the input event being called when I type in the editor, but the drop event is not being called when something is dropped in the editor. The "text" value from the drop event is being added to the editor content, so the editor is clearly receiving a drop event, but the defined event handler is not being called.

The froala-editor and react-froala-wysiwyg sections from my package.json are here:

```
    "froala-editor": "^2.7.0",
    "react-froala-wysiwyg": "^2.7.0-1",
```

Any help would be appreciated.

**Comment by stefanneculai** [comment]
@wittlesouth please subscribe to the drop event as shown in the docs, inside the initialized event: https://www.froala.com/wysiwyg-editor/examples/drop-content.

**Comment by wittlesouth** [comment]
Thank you for your useful suggestion to read the documentation, it is my second favorite response to a technical support question, trailing only “it’s working as designed”.

I refer you to your own documentation here: https://github.com/froala/react-froala-wysiwyg <https://github.com/froala/react-froala-wysiwyg>

Please read the section titled “Events and Methods”, specifically that “Events can be passed in with the options, with a key events and object where the key is the event name and the value is the callback function”. This section provides a link to the Froala editor docs for which events are supported, and drop is one of them.

The code referred to in issue #50 seems to comply with the example in the “Events and Methods” section, but does not result in the drop event handler being called. So my efforts to follow the documentation appear to be in vain.

I would prefer to avoid writing Froala-editor specific initialization code if possible. If this isn’t an issue that you’re going to fix, you might want to update the react-froala-wysiwg documentation to explicitly identify which events can have handlers passed in via the configuration object, and which cannot.

-Eric

**Comment by wittlesouth** [comment]
So in case anyone else stumbles on this issue later, here's how I addressed this issue.

The documentation linked above ([https://www.froala.com/wysiwyg-editor/examples/drop-content](https://www.froala.com/wysiwyg-editor/examples/drop-content)) was mildly useful in that it indicates that I need to use the on method of the editor after instantiation to assign a handler for drop.

If you add a listener to the initialized event in your config object, you can assign a drop listener. You'll need to bind the editor and dropEvent to that listener, as it will not be called with the same arguments you see in the documentation unless you do so. Here is the events section of my configuration object:

```
      events: {
        'froalaEditor.initialized': (e, editor) => {
          editor.events.on('drop', this.onImageDrop.bind(null, e, editor), true)
        }
      },
```

The above results in my drop handler being called as expected. Hopefully the documentation for this React component will be updated to distinguish which events can be assigned in configuration, and which need to be assigned after initialization.

**Comment by stefanneculai** [comment]
@wittlesouth the drop event is the only exception from the details in the docs. That's caused because of an event which we needed in the editor and had to add this restriction. We're looking for a workaround to this matter.

**Comment by kzatin** [comment]
> So in case anyone else stumbles on this issue later, here's how I addressed this issue.
> 
> The documentation linked above (https://www.froala.com/wysiwyg-editor/examples/drop-content) was mildly useful in that it indicates that I need to use the on method of editor.events **after initialization** to assign a handler for drop.
> 
> If you add a listener to the initialized event in your config object, you can assign a drop listener. You'll need to bind the editor and dropEvent to that listener, as it will not be called with the same arguments you see in the documentation unless you do so. Here is the events section of my configuration object, the function I'm trying to register to handle the drop event is `this.onImageDrop`:
> 
> ```
>       events: {
>         'froalaEditor.initialized': (e, editor) => {
>           editor.events.on('drop', this.onImageDrop.bind(null, e, editor), true)
>         }
>       },
> ```
> 
> The above results in my drop handler being called as expected. Hopefully the documentation for this React component will be updated to distinguish which events can be assigned in configuration, and which need to be assigned after initialization.

How to implement this in ReactJs
