### ISSUE TITLE
Cannot access react component 'this' on froala events

### ISSUE THREAD

**Issue by Plash-jindal** [froala/react-froala-wysiwyg#52]
Can you tell me how to bind this with the froala events so that I can change the state before the file is uploaded?

Moreover how to not upload the file to the froala server?

I know the way to upload it to the server with froala editor but I want to send the file along with the other data, so can you tell me the way for that?

**Comment by kyleroberthammond** [comment]
You can bind a function in the constructor of your component. Then pass the function into config object. That seems to work. I dont know about uploading etc.

Heres my example.

export class TextareaField extends Component{
    
  constructor(props) {
    super(props)
    this.state = {}

    this.handleModelChange = this.handleModelChange.bind(this)

    this.handleFocusChange = this.handleFocusChange.bind(this)
  }

  handleModelChange(model){
    this.props.input.onChange(model)
    this.props.input.onBlur(model)
  }

  handleFocusChange(){
    console.log(this)
  }

  render(){

    const { label, input , className, meta, placeholder} = this.props;
    const { touched, error, warning } = meta;

    let config = {
          placeholder: "Edit Me",
          events : {
            'froalaEditor.focus' : this.handleFocusChange
          }
    }

    return (
      <div>
        <div className={`${touched && error ? 'has-danger' : '' } ${touched && warning ? 'has-warning' : '' }`}>
          <div className="form-group">
            {label ? <label className="control-label col-md-2">{label}</label> : ''}

            <div className={label ? 'col-md-10' : 'col-md-12'}>
                
                <FroalaEditor
                  tag='textarea'
                  config={config}
                  model={this.props.input.value}
                  onModelChange={this.handleModelChange}
                />

            </div>
          </div>
        </div>

        <div className="form-group">
          <div className={label ? 'col-md-offset-2 col-md-10' : 'col-md-12'}>
              <div className="text-help">
                {touched && error ? `Error: ${error}` : ''}
                {touched && warning ? `Warning: ${warning}` : ''}
              </div>
          </div>
        </div>
      </div>
    );


  }



}
