### ISSUE TITLE
Override default commands

### ISSUE THREAD

**Issue by bholdt** [froala/react-froala-wysiwyg#53]
Is there a way to override the default behaviour for one of the commands. For example, instead of the html for underline to be <u>text</u>, I want to override to be <span style="text-decoration: underline;">text</span>.

Is this possible?

**Comment by stefanneculai** [comment]
@bholdt it is best to define new commands instead of overriding the existing ones: https://www.froala.com/wysiwyg-editor/examples/custom-buttons

**Comment by virendra05** [comment]
i have a fuction called as 
    function cleanBlankSpaces (el) {
 
      if (typeof el == 'undefined') el = editor.el;

      if (el && ['SCRIPT', 'STYLE', 'PRE'].indexOf(el.tagName) >= 0) return false;

      var walker = editor.doc.createTreeWalker(el, NodeFilter.SHOW_TEXT, editor.node.filter(function (node) {

          return node.textContent.match(/([ \n]{2,})|(^[ \n]{1,})|([ \n]{1,}$)/g) != null;
        }), false);

      while (walker.nextNode()) {

        var node = walker.currentNode;

        if (isPreformatted(node.parentNode, true)) continue;

        var is_block_or_element = editor.node.isBlock(node.parentNode) || editor.node.isElement(node.parentNode);

        // Remove middle spaces.
        // Replace new lines with spaces.
        // Replace begin/end spaces.
        var txt = node.textContent
          .replace(/(?!^)( ){2,}(?!$)/g, ' ')
          .replace(/\n/g, ' ')
          .replace(/^[ ]{2,}/g, ' ')
          .replace(/[ ]{2,}$/g, ' ');

        if (is_block_or_element) {
          var p_node = node.previousSibling;
          var n_node = node.nextSibling;

          if (p_node && n_node && txt == ' ') {
            if (editor.node.isBlock(p_node) && editor.node.isBlock(n_node)) {
              txt = '';
            }
            else {
              txt = ' ';
            }
          }
          else {

            // No previous siblings.
            if (!p_node) txt = txt.replace(/^ */,'');

            // No next siblings.
            if (!n_node) txt = txt.replace(/ *$/,'');
          }
        }

        node.textContent = txt;
      }
    } 
in froala plugins. but now I want to override the function how can I do it
