### ISSUE TITLE
Mention library

### ISSUE THREAD

**Issue by bufordtaylor** [froala/react-froala-wysiwyg#56]
I'm struggling to find an @ mention library that is compatible with froala's react library. I've looked at At.js, but there is no straightforward react/vanilla only library. Does anyone have any suggestions?

**Comment by stefanneculai** [comment]
@bufordtaylor unfortunately, at this moment we don't have other integration than At.JS. We're looking forward to add a plugin over the editor directly, however we cannot provide an ETA for this yet.
