### ISSUE TITLE
image upload to cloudinary

### ISSUE THREAD

**Issue by gogogous88** [froala/react-froala-wysiwyg#59]
with these code:
`render() {
    const config = {
      placeholderText: "Edit Your  Here!",
      charCounterCount: false,
      imageUploadURL: "https://api.cloudinary.com/v1_1/youname/image/upload",
      imageUploadParams: {
        api_key: "api_key",
        upload_preset: "upload_preset"
      }
    };
    return (
      <div style={{ marginLeft: 100, marginTop: 100, marginRight: 100 }}>
        <FroalaEditor
          model={this.state.model.content}
          onModelChange={this.handleModelChange.bind(this)}
          config={config}
          tag="textarea"
        />`

I CAN ONLY DONE HALF OF UPLOADING(CLOUDINARY HAS NEW IMAGES POSTED BUT THE RESPONSE CANNOT SHOW IN THE <FROALAEDITORVIEW>.

THERE WAS SOMEONE HELPED IN JQUERY PART HERE:[](http://jsfiddle.net/tocker/xnsbjc01/),they used parseJson to solve the problem.

`var _parseJSON = jQuery.parseJSON;
jQuery.parseJSON = function(j) {
    var response = _parseJSON(j);
    // TODO proper selection of url / secure_url based on the document link
    response.link = response.url; // Froala expects `link`
    return response;
};`

could anyone help to make it possible to work also in REACT? Thank you very much!

**Comment by stefanneculai** [comment]
@gogogous88 we would recommend instead of changing the parseJSON to use the `image.uploaded` callback, parse the response and then insert the image: https://github.com/froala/wysiwyg-editor/issues/2112#issuecomment-321190805.

**Comment by sjakati98** [comment]
I'm having a similar problem. I am able to upload my image to cloudinary, as in the upload will go to 100%, but then it says "Something went wrong". I am using the react-froala FroalaEditor component, so I am not really sure where I am supposed to put the parseJSON. @stefanneculai
