### ISSUE TITLE
Can't hit enter in the react-froala text editor.

### ISSUE THREAD

**Issue by imparvez** [froala/react-froala-wysiwyg#60]
@stefanneculai : I have implemented `react-froala-WYSIWYG` editor inside my project but at the same time, I observe a weird behavior where my user experience is getting deteriorated.
For eg.
I can't hit `enter` key in the text editor which couldn't take me to next line. To do so, I have to press `shift+enter` but at the back of `html`, structuring breaks down.

My configuration is very simple and are as follow:
`webpack`:
```
plugins: [
      new ExtractTextPlugin('[name].css', {allChunks: true}),
      new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery"
      }),
    ]
```

In Component where I am using `froala`:
```
// Require Editor JS files.
import 'froala-editor/js/froala_editor.pkgd.min.js';

// Require Editor CSS files.
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';

// Require Font Awesome.
import 'font-awesome/css/font-awesome.css';
import FroalaEditor from 'react-froala-wysiwyg';
import FroalaEditorView from 'react-froala-wysiwyg/FroalaEditorView';

this.state = {
            htmlUpdatedContent: ''
}

this.handleModelChange = this.handleModelChange.bind(this); // Froala Editor

handleModelChange(model) {
        this.setState({
            htmlUpdatedContent: model
        });
 }

<FroalaEditor
    model={this.state.htmlUpdatedContent}
    onModelChange={this.handleModelChange}
/>
```

As far as I know, I am not missing anything in the configuration part, and the data is getting updated and I can fetch the same data too but what disturbs me a lot is that I can't hit `enter`.

**User Story: Terms and Conditions**
I tried to write `Terms and Conditions` in the editor and copy pasted the list of terms and condition in the editor which result into breaking HTML structure which you can find it in the attached images.

**HTML Preview:**
![html-preview](https://user-images.githubusercontent.com/3184430/34565574-6417a780-f181-11e7-9ebd-cf058cc18ab5.png)

**Text Editor:**
![text-editor](https://user-images.githubusercontent.com/3184430/34565577-648cfe18-f181-11e7-9084-9ac6632a04c1.png)

**Comment by stefanneculai** [comment]
@imparvez I believe that you have there another JS on the page which stops the enter key event from propagating over to the editor. Please check on that.
