### ISSUE TITLE
Updating placeholderText after initialization

### ISSUE THREAD

**Issue by brycedarling** [froala/react-froala-wysiwyg#65]
Hello, I am using the config attribute to set the placeholder text of the `FroalaEditor` component:

```
<FroalaEditor
  tag="textarea"
  config={{ placeholderText: this.state.placeholder }}
/>
```

However, when the placeholder state changes the FroalaEditor placeholder text never updates.

I saw in another issue that showed you could do the following to update the placeholder text:

```
$('.selector').data('froala.editor').opts.placeholderText = 'foobar';
$('.selector').froalaEditor('placeholder.refresh');
```

However, I don't see how I can do something similar with the `FroalaEditor` component in React. I'd like to stay away from making jQuery calls in my React app if possible but I guess I will if need be for now... I really wish I didn't even need the jQuery dependency in the first place but I like the editor so much I am willing to look past this.

Any help would be appreciated! Thank you!

**Comment by brycedarling** [comment]
I was able to get this to work using a ref, lifecycle hook, and the direct jQuery calls.

Added a `ref` to the `FroalaEditor`:

```
<FroalaEditor
  tag="textarea"
  ref="editor"
  config={{ placeholderText: this.state.placeholder }}
/>
```

Added a lifecycle method that checks to see if there is a new placeholder value and if so make the jQuery calls:

```
  componentWillReceiveProps(newProps) {
    const oldPlaceholder = this.props.placeholder;
    const { placeholder } = newProps;
    if (oldPlaceholder === placeholder) return;
    const { editor } = this.refs;
    if (!editor) return;
    const { $element } = this.refs.editor;
    if (!$element) return;
    $element.data('froala.editor').opts.placeholderText = placeholder;
    $element.froalaEditor('placeholder.refresh');
  }
```

This seems to work fine and will serve my purposes for now. I would love to know if this is the suggested way to get this working though. Thanks!

**Comment by stefanneculai** [comment]
@brycedarling the editor options cannot be changed once the editor was initialized. It is not a React problem, we designed the editor this way. The main reason for that was that there are very few cases when changing an option after initializing is necessary and to do it, there was a lot of code which we should put there in the editor, especially for options like placeholder where you have to do a custom action after changing it. For such cases, we recommend destroying the editor instance and initializing it again.

**Comment by brycedarling** [comment]
I know it's not a React problem, that's why I brought it up. This component doesn't function like basically any other React component does/should, which is why I brought it up in the first place. React means it is supposed to react to changes, if a prop is updated it should re-render. I consider this a flaw and an unfortunate design decision on top of needing the jQuery dependency which already feels wrong in a React app. Seems like a bandaid over not having true React support. Sometimes to do things the right way you need to put in the work, regardless of how much extra code you need to add lol, bad excuse if you ask me. Please reconsider :) Thanks!

**Comment by dianaprajescu** [comment]
@brycedarling don't get us wrong. We're putting in this editor a lot of work, but this doesn't necessarily mean extra code. For performance reasons, we are doing our best to keep the plugin's size as small as possible, by optimizing the code and not adding a lot of extra code where we can avoid it. As for the jQuery dependency, we will remove it in the next major release this year.

**Comment by brycedarling** [comment]
@dianaprajescu The removal of the jQuery depedency sounds AMAZING!!! Awesome work! :) I really appreciate all your effort on this, it's the nicest wysiwyg editor I've used, and it makes me happy knowing it'll become more of a first class React citizen. As long as I can still hack around the placeholder thing, because it's behavior my app needs, I can totally live with that. Really looking forward to trying that next major release! Thanks!
