### ISSUE TITLE
`paragraphFormat` setting not respected before text selection.

### ISSUE THREAD

**Issue by topher515** [froala/react-froala-wysiwyg#67]
My Froala editor's `paragraphFormat` setting works as expected after selecting text in the editor, but not before hand.

### Editor before selection
Note that "Normal" appears, where I would expect "P"

<img width="686" alt="screen shot 2018-02-07 at 4 29 48 pm" src="https://user-images.githubusercontent.com/24050/35943131-1b9341da-0c26-11e8-977c-57a64aa25ec7.png">

### Editor when selecting H1
<img width="685" alt="screen shot 2018-02-07 at 4 29 56 pm" src="https://user-images.githubusercontent.com/24050/35943225-593c4f2c-0c26-11e8-9437-ed910c8a1589.png">

### Editor when selecting P
<img width="684" alt="screen shot 2018-02-07 at 4 30 03 pm" src="https://user-images.githubusercontent.com/24050/35943157-29f9eaf8-0c26-11e8-8ef7-2f03dcb692b4.png">

### Foobar.jsx

My Froala component is configured like so...

```
    <FroalaEditor config={{
      theme: 'foobar',
      typingTimer: 250,
      placeholderText: '',
      paragraphFormatSelection: true, 
      paragraphFormat: {
        N: 'P',    // The setting that I expect to control this
        H1: 'H1',
        H2: 'H2',
        H3: 'H3',
        H4: 'H4'
      },
      ...config
    }} {...props} />
```

### Foobar.css

We also do some CSS hacking to shrink the `paragraphFormat` box.

```
.foobar-theme.fr-toolbar .fr-command.fr-btn.fr-dropdown.fr-selection[id^=paragraphFormat] {
  width: 50px; // Max-width p, h1, h2, etc. dropdown box
}
```

**Comment by stefanneculai** [comment]
Should be fixed on the master branch from the editor: https://github.com/froala/wysiwyg-editor.
