### ISSUE TITLE
editor.image.insert either two images or incorrect redux state

### ISSUE THREAD

**Issue by mattb1981** [froala/react-froala-wysiwyg#68]
Using: 2.7.3

Can this be reopened, using the above fixes the issue with double images, but it means that just a br tag is added to the state of the editor (we store the state in redux), e.g.:

            editor.image.insert(imageUrl, true, null, editor.image.get(), null);

Gives this in redux:
```
{
  Editor: {
    editorState"""<p><br></p>"
  }
}
```

Where as using means we get the correct redux state:

            editor.image.insert(imageUrl);

Appears there are two onModalChange events fired:

1.

```
Editor:{
    editorState: null => "<p><br></p>"
}
```

2.

```
Editor: {
    editorState"<p><br></p>""<p><img src=\"http://ourimageurl=\" style=\"width: 300px;\" class=\"fr-fic fr-dib\"><br></p>"
}
```
But leaves us with this on the editor:

![image](https://user-images.githubusercontent.com/33954261/36039163-9cef9686-0db9-11e8-8cc8-d44916d7ce0e.png)

**Comment by mattb1981** [comment]
Upgraded to 2.7.5 and the issue persists

**Comment by stefanneculai** [comment]
@mattb1981 are you still having this problem? Could you make a repo where we can reproduce it?

**Comment by stefanneculai** [comment]
I am closing this. Would be happy to check it again if we have enough details to reproduce it.
