### ISSUE TITLE
FroalaEditorView Component is disabling click events

### ISSUE THREAD

**Issue by dcporter44** [froala/react-froala-wysiwyg#69]
For some reason when using the FroalaEditorView component and using edit.off, click events don't seem to work. For example, when clicking on anchor tags or trying to click play on an embedded Youtube video. Is there a setting to allow click events?

**Comment by stefanneculai** [comment]
@dcporter44 the editor is designed to prevent all interactions while the edit is disabled. This includes opening external links or interacting with other editor content.
