### ISSUE TITLE
Froala React Typings

### ISSUE THREAD

**Issue by inunotaisho26** [froala/react-froala-wysiwyg#70]
Hi, 
I have already purchased a froala license and I would like to use froala editor in my react application. The thing is I am using I am using tsx as I am a typescript user. I don't know enough about froala to be making the type definitions myself. I would, however, be willing to test it before the typings are actually released.

Repo I am would be using them on: https://github.com/inunotaisho26/inunotaisho-react

**Comment by stefanneculai** [comment]
Duplicate of #16. They'll be added during a sprint in the following weeks. Sorry to keep you guys waiting.
