### ISSUE TITLE
Inserting a video makes entire fr-view div a click event for the video

### ISSUE THREAD

**Issue by posijuur** [froala/react-froala-wysiwyg#72]
After add video in editor, I can not go on a new line. use react-froala-wysiwyg
How can I do this? Why did you no fix this bug in react-froala-wysiwyg, but froala-wysiwyg works good((

**Comment by stefanneculai** [comment]
@posijuur the current [Github master for the editor](https://github.com/froala/wysiwyg-editor) adds the possibility of adding a new line by clicking above/below. The current Github master is still under development and this change will be included in version 2.7.6. In the meanwhile, you could use the Line Breaker tool.

**Comment by posijuur** [comment]
When will version 2.7.6 appear? Ask please

**Comment by stefanneculai** [comment]
We don't think it's right to set expectations that may not be met due to shifting schedules. Therefore, we can't release any information about when the new realease may become available.
