### ISSUE TITLE
how can I fire froalaEditor events in react?

### ISSUE THREAD

**Issue by yquan** [froala/react-froala-wysiwyg#73]
say for example if I'd click a button to focus froala editor via jquery, I could do:

```
$('#mybutton').on('click', function(){
	$('#froala-editor').froalaEditor('events.focus');
});
```
but how can I achieve the same in react? thanks in advance!

**Comment by stefanneculai** [comment]
For that it would be best to use the manual controls: https://github.com/froala/react-froala-wysiwyg#manual-instantiation.
