### ISSUE TITLE
Custom plugins and React

### ISSUE THREAD

**Issue by simoroshka** [froala/react-froala-wysiwyg#74]
Is there an example or a guide of including your own plugins when using Froala with React? 
Where is the right place to put them?

**Comment by mbensch** [comment]
We have them in a `lib/froala` folder in our project tree and just import them in our wrapper and add them to the list of plugins.

**Comment by stefanneculai** [comment]
@simoroshka you could just put them in a folder as @mbensch suggested and then import them as the other editor plugins:

```
// Require Editor JS files.
import 'froala-editor/js/froala_editor.pkgd.min.js';
```

**Comment by isimisi** [comment]
This didn't work for me. 

Creating a custom plugin:

// @lib/froala/myPlugin.ts
```ts
import Froala from "froala-editor";

(function (FroalaEditor: typeof Froala) {

FroalaEditor.PLUGINS.myPlugin = function (editor) {

  function test() {
    console.log("test")
  }

  return {
    test,
  }

}

})(Froala)
```

// @components/FroalaEditor
```tsx
import Froala from "react-froala-wysiwyg";
import "froala-editor/css/froala_style.min.css";
import "froala-editor/css/froala_editor.pkgd.min.css";
import "froala-editor/css/third_party/embedly.min.css";
import "froala-editor/js/froala_editor.pkgd.min.js";
import "@lib/froala/myPlugin";
import "froala-editor/js/plugins.pkgd.min.js";
import "froala-editor/js/third_party/embedly.min.js";

export default function FroalaEditor() {
  return (
    <Froala
      tag="textarea"
      config={{
        events: {
          initialized() {
            this.myPlugin.test();
          },
        },
      }}
// other props...
    />
  );
}

```

This will throw an error: Uncaught TypeError: Cannot read properties of undefined (reading 'test')

The plugin works when I'm using vanilla froala-editor: https://jsfiddle.net/x0tm2e5h/2/
