### ISSUE TITLE
Custom Buttons

### ISSUE THREAD

**Issue by AneudysOrtiz** [froala/react-froala-wysiwyg#77]
Is there any way that I can add custom buttons to the toolbar using React?

**Comment by DineshMadhanlal** [comment]
```
import 'froala-editor/js/froala_editor.pkgd.min';
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';
import 'font-awesome/css/font-awesome.css';
import FroalaEditor from 'react-froala-wysiwyg';

  componentDidMount() {
    $.FroalaEditor.DefineIcon('check', { NAME: 'check-square' });
    $.FroalaEditor.RegisterCommand('check', {
      title: 'check-box',
      focus: true,
      undo: true,
      refreshAfterCallback: false,
      callback: () => {
        this.setState({ model: this.state.model + '<input type="checkbox" />' });
      },
    });
  }

  config = {
    placeholderText: 'Your notes here....',
    heightMin: 250,
    heightMax: 400,
    colorsHEXInput: false,
    autoFocus: true,
    toolbarBottom: true,
    linkAlwaysBlank: true,
    fontFamilySelection: true,
    fontSizeSelection: true,
    paragraphFormatSelection: true,
    htmlExecuteScripts: true,
    iframe: true,
    tabSpaces: 4,
    pluginsEnabled: ['align', 'charCounter', 'codeBeautifier', 'codeView', 'colors', 'draggable', 'embedly', 'emoticons', 'entities', 'file', 'fontFamily', 'fontSize', 'fullscreen', 'image', 'imageManager', 'inlineStyle', 'lineBreaker', 'link', 'lists', 'paragraphFormat', 'paragraphStyle', 'quickInsert', 'quote', 'save', 'table', 'url', 'video', 'wordPaste'],
    toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'fontFamily', 'fontSize', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'check', '|', 'insertLink', 'insertImage', 'insertVideo', 'embedly', 'insertFile', 'insertTable', '|', 'emoticons', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'spellChecker', 'help', 'html', '|', 'undo', 'redo'],
    toolbarButtonsMD: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'fontFamily', 'fontSize', 'color', 'inlineStyle', 'paragraphStyle', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'check', '|', 'insertLink', 'insertImage', 'insertVideo', 'embedly', 'insertFile', 'insertTable', '|', 'emoticons', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'spellChecker', 'help', 'html', '|', 'undo', 'redo'],
    toolbarButtonsSM: ['bold', 'italic', 'underline', 'strikeThrough', '|', 'fontFamily', 'fontSize', 'color', '|', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'check', '|', 'insertLink', 'insertImage', 'insertVideo', 'embedly', 'insertFile', 'insertTable', '|', 'emoticons', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'spellChecker', 'help', 'html', '|', 'undo', 'redo'],
    toolbarButtonsXS: ['bold', 'italic', 'underline', '|', 'fontFamily', 'fontSize', 'color', '|', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'check', '|', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '|', 'insertHR', 'selectAll', 'clearFormatting', '|', 'spellChecker', '|', 'undo', 'redo'],
  };


  handleModelChange = (data) => {
    this.setState({
      model: data,
    });
    this.saveEvent();
  }

  <FroalaEditor
         config={this.config}
         model={this.state.model}
         onModelChange={this.handleModelChange}
   />
```
Yeah, we call add custom buttons in the toolbar. Please refer the above code for reference,

**Comment by truonghoangphuc** [comment]
Hi @DineshMadhanlal

When I do as your comment, it return with error $ is not defined. Before that, my froala-editor working correctly as expect.

ps: my project create from 'create-react-app' and I edited webpack.config.dev.js (and webpack.config.prod.js) of node_modules/react-scripts/config to load jQuery for Froala:
new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery"
    })

Thanks,

**Comment by DineshMadhanlal** [comment]
Did you import jQuery?
`import $ from 'jquery';`

**Comment by DineshMadhanlal** [comment]
Could you send the code and images if possible to debug your issue?

**Comment by truonghoangphuc** [comment]
Hi @DineshMadhanlal 
I just fixed, this is a mistake from my code cause I put define in ComponentDidMount and config inside render.


Thanks,

**Comment by DineshMadhanlal** [comment]
Cool @truonghoangphuc :+1:

**Comment by export-mike** [comment]
@truonghoangphuc looks like I'm making the same mistake you did where the custom buttons are not displaying, after reading your comment I don't follow.

```js
componentDidMount() {
   $.FroalaEditor.DefineIcon('check', { NAME: 'check-square' });
   $.FroalaEditor.RegisterCommand('check', {
      title: 'check-box',
      focus: true,
      undo: true,
      refreshAfterCallback: false,
      callback: () => {
        this.setState({ model: this.state.model + '<input type="checkbox" />' });
      },
    });
}
render() {
    return <ReactFroalaEditor
		   config={{
					toolbarButtons: ['undo', 'redo' , 'bold', '|', 'check']
				}}
				ref={editor => {this.editor = editor;} }
				tag='textarea'
			/>
}

```

**Comment by vijayshukla30** [comment]
@export-mike I move componentDidMount code to render itself, just before defining config.

**Comment by GaddMaster** [comment]
Hi

When I add your "plugin enabled" config line, none my plugins show. 

Such as code view, embedly, align etc.

Why is this ?

Daniel

**Comment by GaddMaster** [comment]
Hi All.

Is using jQuery the only way at making custom buttons. Is there not a more React way?

Daniel

**Comment by Felix-Indoing** [comment]
Froala is removing dependence on JQuery, so what is the proper way to add a customize button for now?

**Comment by jyhong666** [comment]
Froala is removing dependence on JQuery, so what is the proper way to add a customize button for now?

**Comment by nsabourin** [comment]
@jyhong666 I was wondering about the same thing. Is someone have a new proper way to do it ?

**Comment by nsabourin** [comment]
I found how to do it ! This is how i did it.

```
import FroalaEditor from "froala-editor";
import FroalaEditorComponent from "react-froala-wysiwyg";

...

constructor(props) {
        super(props);
        FroalaEditor.DefineIcon('insertTemplateIcon', {FA5NAME: 'plus',template:'font_awesome_5r'});
        FroalaEditor.RegisterCommand('insertTemplateButton', {
            title: 'Insert variable',
            type: 'dropdown',
            icon:'insertTemplateIcon',
            options: {
                apple: 'apple'
            },
            focus: true,
            undo: true,
            refreshAfterCallback: true,
            callback: function (cmd, val) {
                this.html.insert(val);
            }
        });
    }

render() {
    return (
        <FroalaEditorComponent />
    );
}
```

**Comment by sivako** [comment]
@nsabourin, Glad to hear a solution for react. But I am not able to make it work with this code snippet. (component renders without error and without new icon),  Do I need to add any other config?

import React from "react";

import FroalaEditor from 'froala-editor';
import FroalaEditorComponent from 'react-froala-wysiwyg';


class MyEditor extends React.Component {

	constructor(props) {
		super(props);
		FroalaEditor.DefineIcon('insertTemplateIcon', { FA5NAME: 'plus', template: 'font_awesome_5r' });
		FroalaEditor.RegisterCommand('insertTemplateButton', {
			title: 'Insert variable',
			type: 'dropdown',
			icon: 'insertTemplateIcon',
			options: {
				apple: 'apple',
			},
			focus: true,
			undo: true,
			refreshAfterCallback: true,
			callback: function (cmd, val) {
				this.html.insert(val);
			},
		});
  }

	render() {
		return <FroalaEditorComponent />;
	}
}

// In App file, am doing this
import 'froala-editor/js/froala_editor.pkgd.min.js';
import 'froala-editor/css/froala_style.min.css';
import 'froala-editor/css/froala_editor.pkgd.min.css';
import $ from 'jquery';  // without this also seems fine
// @ts-ignore
window.$ = $;  // without this also seems fine

Any help or pointers?

Thanks

**Comment by andrewwood2** [comment]
Thanks to @nsabourin for the snippet. Here's another example in case others come across this. Note (perhaps slightly confusingly) I have different names for the default imports.

`import React from 'react'
import Froala from 'froala-editor'
import FroalaEditor from 'react-froala-wysiwyg'

const FroalaContainer: React.FC = () => {

   const doSomething = () => {
     ... something
   }

    Froala.DefineIcon('findAndReplace', { SVG_KEY: 'search' })
    Froala.RegisterCommand('findAndReplace', {
      title: 'Find and replace',
      icon: 'findAndReplace',
      focus: true,
      undo: false,
      refreshAfterCallback: true,
      callback: function() {
        doSomething()
      }
  })

  const froalaConfig = {
    toolbarButtons: ['undo', 'redo', 'findAndReplace']
    ...other-config
  } 
  
  return (
    <FroalaEditor 
      config={froalaConfig}
      ... other-options
    />
  )
}
`
