### ISSUE TITLE
v2.8.1 breaks server-side rendering

### ISSUE THREAD

**Issue by SamuelBolduc** [froala/react-froala-wysiwyg#81]
```
ReferenceError: window is not defined
    at Object.<anonymous> (/var/www/web/node_modules/react-froala-wysiwyg/index.js:1:300)
    [...]
```
Our development `package.json` specified version `^2.7.3` for `react-froala-wysiwyg`, and deployments (in our dev infrastructure) started failing this morning with the error above. Since the caret means "latest version that does not change major" it probably started installing `2.8.1`.

We were already using Webpack 4 and it worked well with `2.7.3`, so I don't really see what went wrong. Anyways, specifying `2.7.3` without the caret fixed the error.

**Comment by adueck** [comment]
@Cokser can you please post a full example of how you did this? (With nextjs?)

**Comment by cloud-github** [comment]
I amalso getting same issue 

> ReferenceError: window is not defined
    at Object.<anonymous> 

Froala latest version : ^2.9.1

**Comment by stefanneculai** [comment]
Please see https://github.com/froala/react-froala-wysiwyg/issues/89#issuecomment-429782077.
