### ISSUE TITLE
events in code view?

### ISSUE THREAD

**Issue by kirkbross** [froala/react-froala-wysiwyg#82]
I use this in my config to catch keypress in the wysiwyg view:

`events: {
        'froalaEditor.focus': this.onFocus,
        'froalaEditor.keydown': this.stopPropagation,
}`

But it doesn't work in code / html view.

**How do I catch events when in code / html view?**

(I'm using arrow keys for another function upstream and need to stopPropagation to prevent bubbleup)

**Comment by EmanuelaGr** [comment]
I have the same problem, I need to use "froalaEditor.image.beforeUpload"event and it's not working...did you find any solution for this?

**Comment by EmanuelaGr** [comment]
Any update about a solution for this?

**Comment by joseluizjr** [comment]
Any feedback on this request?

**Comment by kirkbross** [comment]
No luck. You'd probably have to write something custom targeting `textarea` with a class of `fr-code`.

**Comment by kirkbross** [comment]
With jQuery it would be: 

```
$('.fr-code').change(function() {
// whatever
});
```

**Comment by EmanuelaGr** [comment]
Any update how I can resolve this problem?

**Comment by spondbob** [comment]
There's a bug with `events` initialisation. See #93.

**Comment by stefanneculai** [comment]
At this moment, in code view, events are designed not to be triggered. In order to add this feature, please suggest it here: https://wysiwyg-editor-roadmap.froala.com/public.
