### ISSUE TITLE
Issue with BR and new paragraph

### ISSUE THREAD

**Issue by joseluizjr** [froala/react-froala-wysiwyg#83]
When using with react the following happens (with an empty editor):

1. Types some text: ABC 
Source code: <p>ABC</p>
2. Press ENTER
Source Code: 
<p>ABC</p>

<p>
	<br>
</p>
Observation: it stays in the SAME line, it doesn't go to a new line.

The configutation is the following:

const config = {
  enter: $.FroalaEditor.ENTER_P
}

Can you guys help me with this issue?

@dtiziani
![evidence](https://user-images.githubusercontent.com/25259402/40448414-d26044a8-5eab-11e8-8663-546d519a348f.png)

Version used:     "react-froala-wysiwyg": "^2.8.1"

**Comment by joseluizjr** [comment]
Any feedback on this request?

**Comment by stefanneculai** [comment]
Most likely you're making a two-way data binding which sets the editor content back when the content is changed in the editor. The editor is using HTML underneath and setting another HTML while the cursor is inside the editable area would result in losing the current selection. 

It appears to be similar to https://github.com/froala/react-froala-wysiwyg/issues/61#issuecomment-368644151.
