### ISSUE TITLE
Testing with Enzyme / Jest hurdle

### ISSUE THREAD

**Issue by robseriousgit** [froala/react-froala-wysiwyg#84]
Hi,

When trying to make our tests pass again after including your component we had some issues with jQuery and the test DOM.

We have got it working but had to jam some pretty unsightly stuff into a `setup.js` file for Jest.

In short, we had to include jQuery, include the fraola package, initialise it, then define some methods on the global window that didn't exist, e.g. domain, getSelection

Not sure if anyone is testing this in a similar way, but we're wondering if anyone has done this in a nicer way.

Snippet:

```
const $ = require('jquery')
require('froala-editor/js/froala_editor.pkgd.min.js')()

const { JSDOM } = require('jsdom')

const jsdom = new JSDOM('<!doctype html><html><body></body></html>')

function copyProps (src, target) {
  const props = Object.getOwnPropertyNames(src)
    .filter(prop => typeof target[prop] === 'undefined')
    .reduce((result, prop) => {
      return Object.assign(
        {},
        result,
        { [prop]: Object.getOwnPropertyDescriptor(src, prop) }
      )
    }, {})
  Object.defineProperties(target, props)
}

global.window = jsdom.window
window.scrollTo = () => {}
window.$ = $
window.document.domain = 'www.hello.you'
window.document.getSelection = () => {}
window.navigator = {
  userAgent: 'node.js'
}
copyProps(window, global)
```

**Comment by stefanneculai** [comment]
@robseriousgit the editor requires jQuery and it is working with the DOM. As per our experiments, it is best not to use `jsdom` for testing as it doesn't reflect what is really happening in the browser. For our internal tests, we're using qunit with a headless chrome.
