### ISSUE TITLE
Using global jQuery

### ISSUE THREAD

**Issue by yuxuan** [froala/react-froala-wysiwyg#87]
My scenario is:  I embed my `react-froala-wysiwyg` app with jquery version 2.2.4 into another application with jquery version 1.9.1 that is lower than froala required version.
In the `createEditor` function, `this.$element = $(this.refs.el);` is using global jquery directly, that causes froala editor not able to be loaded. Do you consider to require the same jquery version as froala editor required?

**Comment by stefanneculai** [comment]
@yuxuan the `react-froala-wysiwyg` doesn't include any jQuery plugin and the `froala-editor` requires jQuery higher than 1.11.0: https://github.com/froala/wysiwyg-editor/blob/master/package.json. Unfortunately, it is not possible to have it work with an older version such as 1.9.1.
