### ISSUE TITLE
Not work with React 16

### ISSUE THREAD

**Issue by ilinyevg** [froala/react-froala-wysiwyg#89]
Hi,

Can you please fix it? 
 
W20180605-12:35:28.088(-7)? (STDERR) ReferenceError: window is not defined
W20180605-12:35:28.088(-7)? (STDERR)     at Object.<anonymous> (/Users/.../.../node_modules/react-froala-wysiwyg/index.js:1:238)
W20180605-12:35:28.088(-7)? (STDERR)     at Module._compile (module.js:652:30)
W20180605-12:35:28.089(-7)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180605-12:35:28.089(-7)? (STDERR)     at Module.load (module.js:565:32)
W20180605-12:35:28.089(-7)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180605-12:35:28.089(-7)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180605-12:35:28.089(-7)? (STDERR)     at Module.require (module.js:596:17)
W20180605-12:35:28.090(-7)? (STDERR)     at require (internal/module.js:11:18)
W20180605-12:35:28.090(-7)? (STDERR)     at npmRequire (/Users/.../.meteor/local/build/programs/server/npm-require.js:133:10)
W20180605-12:35:28.090(-7)? (STDERR)     at Module.useNode (packages/modules-runtime.js:699:18)
W20180605-12:35:28.090(-7)? (STDERR)     at index.js (packages/modules.js:973:8)
W20180605-12:35:28.090(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180605-12:35:28.091(-7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180605-12:35:28.091(-7)? (STDERR)     at HTMLEditor.jsx (imports/ui/components/uniforms/HTMLEditor.jsx:1:456)
W20180605-12:35:28.091(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180605-12:35:28.091(-7)? (STDERR)     at require (packages/modules-runtime.js:238:16)

**Comment by jelenajjo** [comment]
I just ran into same issue, hope will be fixed soon

**Comment by ilinyevg** [comment]
window should be defined in the package. 

Possible workaround

componentWillMount() {
        async function loadEditor() {
            if (typeof window !== 'object') {
                global.window = global;
                global.window.navigator = {};
                await import('react-froala-wysiwyg');
            }
        }

        loadEditor();
    }

**Comment by indapublic** [comment]
Probably you using server side rendering

**Comment by Cokser** [comment]
I'm using SSR, and face with this **bug** .
Any updates on this issue?

**Comment by indapublic** [comment]
@Cokser You can add additional checks. My code (but with another component) example:

```
componentWillReceiveProps() {
    if (!this.quill && !!window && !!document) {
      this.quill = require("react-quill");
    }
  }

  render() {    
    if (!this.quill) {
      return null;
    }
    const ReactQuill = this.quill;
    return (
      <div>
        <ReactQuill
```

**Comment by Cokser** [comment]
@indapublic it didn't helped

**Comment by Cokser** [comment]
I solved my problem with [**this**](https://github.com/zeit/next.js#3-with-no-ssr) way.

**Comment by adueck** [comment]
@Cokser Are you also using Next.js ? Can you please share a full code example of how you got it to work [in this way](https://github.com/zeit/next.js#3-with-no-ssr)?

**Comment by vkhupenia** [comment]
@adueck 
This is the component for FE.
```javascript
import React, { Component } from 'react';
import dynamic from 'next/dynamic';

// Require Editor JS files.
import 'froala-editor/js/froala_editor.pkgd.min.js';
import 'froala-editor/js/third_party/embedly.min.js';


// That's where the magic happens 
const FroalaEditorInput = dynamic(import('react-froala-wysiwyg'), {
  ssr: false
});

class FroalaEditor extends Component {
  constructor(props) {
    super(props);

    this.state = {
      content: props.model
    };

    this.config = {
      key: 'keykeykeykeykeykeykeykeykeykeykeykey ;) ==',
      toolbarButtons: [
        'bold',
        'italic',
        'underline',
        'formatOL',
        'formatUL',
        'insertLink',
      ],
      charCounterMax: 1000,
    }
  }

  handleModelChange = model => {
    this.props.handleEditorChange(model);
  };

  render() {
      return (
        <FroalaEditorInput
          id={this.props.editorId}
          config={this.config}
          model={this.props.model}
          onModelChange={this.props.handleEditorChange}
         />
      );
  }
}

export default FroalaEditor;
```

**Comment by adueck** [comment]
Thanks so much for posting this @vkhupenia but unfortunately it's not working for me with Next.js yet. 😢 

I pasted your component file as is and then imported it, but when I try to load it I see 'loading...' appear for a second and then it crashes with this error in the console.

`ReferenceError: $ is not defined`

**Comment by vkhupenia** [comment]
@adueck 
$ it's a jQuery lib.
You have to install it in your app, because it's required for Froala.

**Comment by adueck** [comment]
@vkhupenia Ah, yes, of course, I should have realized that. Thank you.

I installed Jquery but now I'm getting a different error...

```
app.js:63 Uncaught TypeError: this.$element.froalaEditor is not a function
    at t.value (index.js:1)
    at t.value (index.js:1)
    at commitLifeCycles (react-dom.development.js:14361)
    at commitAllLifeCycles (react-dom.development.js:15462)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at commitRoot (react-dom.development.js:15603)
    at completeRoot (react-dom.development.js:16618)
    at performWorkOnRoot (react-dom.development.js:16563)
    at performWork (react-dom.development.js:16482)
    at performSyncWork (react-dom.development.js:16454)
    at requestWork (react-dom.development.js:16354)
    at scheduleWork$1 (react-dom.development.js:16218)
    at Object.enqueueSetState (react-dom.development.js:11299)
    at LoadableComponent.Component.setState (react.development.js:270)
    at update (loadable.js:266)
    at loadable.js:276
```

**Comment by Hello-artx** [comment]
I am getting this error. Can you help me, please!


> ReferenceError: Element is not defined
> (anonymous function)
> /Users/wutthiphorncharm/Desktop/devToolLive/react-next-starter/node_modules/froala-editor/js/froala_editor.pkgd.min.js:7:416
> (anonymous function)
> /Users/wutthiphorncharm/Desktop/devToolLive/react-next-starter/node_modules/froala-editor/js/froala_editor.pkgd.min.js:7:84
> (anonymous function)
> /Users/wutthiphorncharm/Desktop/devToolLive/react-next-starter/node_modules/froala-editor/js/froala_editor.pkgd.min.js:7:155
> Module._compile
> internal/modules/cjs/loader.js:776:30
> Module._extensions..js
> internal/modules/cjs/loader.js:787:10
> Module.load
> internal/modules/cjs/loader.js:653:32
> tryModuleLoad
> internal/modules/cjs/loader.js:593:12
> Function.Module._load
> internal/modules/cjs/loader.js:585:3
> Module.require
> internal/modules/cjs/loader.js:690:17
> require
> internal/modules/cjs/helpers.js:25:18
> froala-editor/js/froala_editor.pkgd.min.js
> webpack:/external "froala-editor/js/froala_editor.pkgd.min.js":1
> > 1 | module.exports = require("froala-editor/js/froala_editor.pkgd.min.js");
> View compiled
> __webpack_require__
> ./webpack/bootstrap:27
> 24 | // Execute the module function
> 25 | var threw = true;
> 26 | try {
> > 27 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
> | ^  28 | 	threw = false;
> 29 | } finally {
> 30 | 	if(threw) delete installedModules[moduleId];


file next.config.js

> const withCSS = require('@zeit/next-css')
> const withLess = require('@zeit/next-less')
> const webpack = require('webpack');
> 
> const withFonts = require('next-fonts');
> module.exports = withFonts(withLess(withCSS(
>     {
>         webpack: function (config) {
>             config.module.rules.push({
>                 test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
>                 use: {
>                     loader: 'url-loader',
>                     options: {
>                         limit: 100000,
>                         name: '[name].[ext]'
>                     }
>                 }
>             })
>             config.plugins.push(new webpack.ProvidePlugin({
>                 $: 'jquery',
>                 jQuery: 'jquery',
>                 'window.jQuery': 'jquery'
>             }))
>             return config
>         }
>     }
> )));
