### ISSUE TITLE
italic toolbar button is not formatting the text in React 15.5.4

### ISSUE THREAD

**Issue by laxmi-a3logics** [froala/react-froala-wysiwyg#95]
I installed  **react-froala-wysiwyg** with yarn (i.e. yarn add react-froala-wysiwyg --save), Following dependencies are also installed:
├─ babel@6.23.0
├─ font-awesome@4.7.0
├─ froala-editor@2.8.4
├─ jquery@3.3.1
└─ react-froala-wysiwyg@2.8.4
this is the code view
![code_view](https://user-images.githubusercontent.com/12049840/43319800-b6bc2ab4-91c3-11e8-92c6-14643381585f.png)

but the content is not formatting(as italic) in html view.
![html-view](https://user-images.githubusercontent.com/12049840/43319823-cc9a016c-91c3-11e8-8754-47e8597e4587.png)

likewise number list (formatOL) and bullet list (formatUL) is not working properly.

**Comment by stefanneculai** [comment]
It looks like you have some CSS on the page which prevents the `em` to be displayed as italic. Please check for CSS conflicts.
