### ISSUE TITLE
Using FroalaEditorView Component, didn't shows Video content

### ISSUE THREAD

**Issue by Cokser** [froala/react-froala-wysiwyg#96]
- STEP-1. Open Page-A with `<FroalaEditor ... />`
- STEP-2. Add video >> Save content
- STEP-3. Open Page-B with `<FroalaEditorView model={this.props.content} />`

#### Result: Video didn't show up.

**Comment by stefanneculai** [comment]
@Cokser could you please let us know how are you adding the video? If you're uploading it, then please make sure that you set it to upload to your server as the editor uploads it to a blob file by default. https://www.froala.com/wysiwyg-editor/docs/concepts/video/upload

**Comment by Cokser** [comment]
@stefanneculai i'm adding just an usual youtube link

**Comment by vkhupenia** [comment]
@stefanneculai i figured out that **youtube link** is badly parsed by FroalaEditor, not all types of links will correctly shown by the FroalaEditorView Component.

**Comment by stefanneculai** [comment]
@vkhupenia what link are you using?

**Comment by stefanneculai** [comment]
I'm closing this due to lack of response. Would be happy to look into it again if we get more details.
