### ISSUE TITLE
jQuery free solution

### ISSUE THREAD

**Issue by pratikt-cuelogic** [froala/react-froala-wysiwyg#98]
Is it possible to implement it without using jQuery

**Comment by stefanneculai** [comment]
A jQuery free solution will come shortly - we're working on that. :)

**Comment by pratikt-cuelogic** [comment]
@stefanneculai, that would be great !!
May I know tentative plan/date of **jQuery free solution**

**Comment by stefanneculai** [comment]
We'll post updates about that on [our blog](https://www.froala.com/blog) in the upcoming weeks.

**Comment by michael811** [comment]
@stefanneculai 
Any updates on this? I didn't find any blogs on this.

**Comment by pgib** [comment]
Any word on this? Nothing has been shared to the blog or that Confluence page.

**Comment by stefanneculai** [comment]
We are expecting to have public updates for it around the end of March 2019.

**Comment by pgib** [comment]
It's been over a year... Any updates?
